#!/usr/bin/env python3
"""
stego_v2.py — Unicode Steganography V2  (format version 3)
===========================================================
Encrypt pipeline:
    file → zlib compress → AES-256-GCM → compact binary payload
         → base-N invisible Unicode encoding → even-spread embedding → .txt

Decrypt pipeline:
    .txt → extract invisible symbols → length prefix bootstrap
         → base-N decode → AES-256-GCM decrypt → decompress → original file

Key improvements over V1 / format version 2
  ✓  AES-256-GCM (authenticated encryption) — replaces AES-CBC
  ✓  PBKDF2-HMAC-SHA256 (200 000 iters) — replaces raw key repetition
  ✓  Adaptive zlib compression before encryption (skipped when not beneficial)
  ✓  Correct integer base-N arithmetic: n^k >= 256^L, no fractional-bit hacks
       _num_symbols() uses dual log estimates (log2 + ln) and takes their max
       to guarantee the result is never an under-estimate
  ✓  Validated Unicode alphabet profiles sourced from unicode_compat.py
       SAFE      =  11 chars (Tier 1 RELIABLE   — 3.46 bits/sym)
       EXTENDED  =  55 chars (Tier 1+2 GOOD     — 5.78 bits/sym)
       MAX       = 392 chars (Tier 1+2+3 EXPERIMENTAL — 8.62 bits/sym)
       ⚠ MAX alphabet is EXPERIMENTAL: 390/392 chars pass all 13 automated
         Python tests; U+3164 and U+FFA0 fail NFKC/NFKD (collapse to U+1160).
         Cross-platform manual testing (clipboard, Windows/macOS text editors,
         browsers, Android, email) is required before production use of MAX.
  ✓  Key-derived Fisher-Yakes permutation of the validated alphabet
  ✓  Compact binary payload header (MAGIC · version · flags · profile · extension
                                     · payload length · salt · nonce)
  ✓  Bootstrap-safe decryption: fixed unkeyed length prefix encodes
      (profile_id, total_bytes) so decryption never has to guess
  ✓  Capacity check before embedding — rejects impossible payloads early
  ✓  Even-spread sequential embedding — no whole-text permutation
  ✓  Three-stage self-test hierarchy:
       Stage 0 — Unicode alphabet validation (uniqueness, tiers, UTF-8 identity)
       Stage 1 — Base-N arithmetic (11 N values × 13 patterns = 143 cases)
       Stage 2 — Full encrypt → embed → extract → decrypt round-trip

Format version note
  Format version 3 is NOT backward-compatible with version 2.
  The alphabet profiles changed (11/55/409 vs 10/26/122), which also changes
  the bootstrap prefix length from 13 → 12 symbols and all keyed permutations.
  Files produced by version 2 cannot be decoded by this version.

Companion tools (same project directory)
  unicode_compat.py      — Stage 2 Unicode compatibility test suite (392+ candidates,
                           13 automated checks, tier scoring, manual test export)
  validated_alphabets.py — Alphabet data generated by unicode_compat.py
  candidates.json/csv    — Full per-character test database
  compat_report.txt      — Human-readable tier report
  manual_tests.txt       — Copy/paste strings for cross-platform testing

Requirements:  pip install pycryptodome
Usage (interactive):   python stego_v2.py
Usage (CLI):           python stego_v2.py encrypt --help
                       python stego_v2.py decrypt --help
                       python stego_v2.py test
                       python stego_v2.py test-base-n
                       python stego_v2.py test-unicode
"""

from __future__ import annotations

import argparse
import hashlib
import math
import os
import struct
import sys
import tempfile
import unicodedata
import zlib
from typing import Tuple

# ── dependency check ──────────────────────────────────────────────────────────
try:
    from Crypto.Cipher import AES
except ImportError:
    sys.exit(
        "ERROR: pycryptodome is required.\n"
        "  Install: pip install pycryptodome"
    )


# =============================================================================
# §1  CRYPTOGRAPHY — AES-256-GCM + PBKDF2
# =============================================================================

_SALT_LEN  = 16   # bytes
_NONCE_LEN = 12   # bytes (GCM recommended)
_TAG_LEN   = 16   # bytes (GCM auth tag)
_KEY_LEN   = 32   # bytes (AES-256)
_KDF_ITER  = 200_000


def _derive_key(password: str, salt: bytes) -> bytes:
    """PBKDF2-HMAC-SHA256 → 256-bit AES key."""
    return hashlib.pbkdf2_hmac(
        "sha256",
        password.encode("utf-8"),
        salt,
        _KDF_ITER,
        _KEY_LEN,
    )


def _aes_encrypt(plaintext: bytes, password: str
                 ) -> Tuple[bytes, bytes, bytes, bytes]:
    """
    AES-256-GCM encrypt.
    Returns (salt, nonce, ciphertext, auth_tag).
    """
    salt   = os.urandom(_SALT_LEN)
    nonce  = os.urandom(_NONCE_LEN)
    key    = _derive_key(password, salt)
    cipher = AES.new(key, AES.MODE_GCM, nonce=nonce)
    ciphertext, tag = cipher.encrypt_and_digest(plaintext)
    return salt, nonce, ciphertext, tag


def _aes_decrypt(salt: bytes, nonce: bytes, ciphertext: bytes,
                 tag: bytes, password: str) -> bytes:
    """
    AES-256-GCM decrypt + authenticate.
    Raises ValueError on tag mismatch (wrong password or corruption).
    """
    key    = _derive_key(password, salt)
    cipher = AES.new(key, AES.MODE_GCM, nonce=nonce)
    try:
        return cipher.decrypt_and_verify(ciphertext, tag)
    except ValueError:
        raise ValueError(
            "Authentication failed — wrong password or corrupted payload."
        )


# =============================================================================
# §2  COMPRESSION — Adaptive zlib
# =============================================================================

_FLAG_COMPRESSED = 0x01


def _compress(data: bytes) -> Tuple[bytes, bool]:
    """
    Compress with zlib level-9.
    Returns (result_bytes, was_compressed).
    Skips compression when it would increase size.
    """
    compressed = zlib.compress(data, level=9)
    if len(compressed) < len(data):
        return compressed, True
    return data, False


def _decompress(data: bytes) -> bytes:
    return zlib.decompress(data)


# =============================================================================
# §3  BASE-N ARITHMETIC — Pure integer operations
# =============================================================================
#
#  Correct mathematical model
#  ──────────────────────────
#  L bytes represent integers in the range  [0 .. 256^L − 1].
#  To represent every such value in base N, we need k digits where:
#
#      N^k  ≥  256^L
#
#  Therefore the minimum digit count is:
#
#      k  =  ceil( log_N( 256^L ) )
#          =  ceil( L · log(256) / log(N) )
#          =  ceil( L · 8 / log₂(N) )
#
#  Note: for non-power-of-two N, log₂(N) is irrational, so a single
#  floating-point ceil can be off by ±1 due to rounding.  We use two
#  independent log bases and take their max to guarantee no under-estimate.
#  An over-estimate of +1 is harmless: the extra digit is a leading zero.
#
#  Encode process (bytes → digits):
#      value = int.from_bytes(data, "big")    # interpret as one big integer
#      for i in range(k):
#          digits[i] = value % N              # repeated division
#          value    //= N
#      digits.reverse()                       # big-endian order
#
#  Decode process (digits → bytes):
#      value = Σ digits[i] · N^(k−1−i)       # Horner's method
#      return value.to_bytes(L, "big")        # L from payload header
#
#  The decoder must know L (original byte length) to handle leading-zero
#  bytes correctly (e.g., b"\x00\xA7" and b"\xA7" have different meanings).
#  L is preserved in the binary payload header.
#

def _num_symbols(num_bytes: int, n: int) -> int:
    """
    Minimum number of base-n digits needed to represent any byte string of
    length num_bytes — i.e. the smallest k with  n^k >= 256^num_bytes.

    Two independent floating-point paths (log₂ and ln) are evaluated and
    their maximum is returned, so the result is never an under-estimate.

    An over-estimate of 1 is harmless: the extra symbol encodes a leading
    zero digit and round-trips correctly because the decoder knows num_bytes.
    """
    if num_bytes == 0:
        return 0
    if n < 2:
        raise ValueError(f"Alphabet size must be >= 2, got {n}")
    # Path A: via log₂
    k1 = math.ceil(num_bytes * 8.0 / math.log2(n))
    # Path B: via natural log  (independent rounding path)
    k2 = math.ceil(num_bytes * math.log(256.0) / math.log(float(n)))
    return max(k1, k2)


def _encode_bytes_to_digits(data: bytes, n: int) -> list:
    """
    Convert a byte string to a big-endian list of base-n integer digits.

    Returns exactly _num_symbols(len(data), n) digits.  Leading zero digits
    are included so the representation covers the full range [0, 256^len(data)),
    which is essential for round-trip correctness when data starts with 0x00.

    Each returned digit d satisfies  0 <= d < n.
    """
    num_syms = _num_symbols(len(data), n)
    if not data:
        return []
    value  = int.from_bytes(data, "big")
    digits: list = []
    for _ in range(num_syms):
        digits.append(value % n)
        value //= n
    digits.reverse()
    return digits


def _decode_digits_to_bytes(digits: list, n: int, num_bytes: int) -> bytes:
    """
    Reconstruct exactly num_bytes bytes from a sequence of base-n integer digits.

    num_bytes MUST equal the original byte-string length used during encoding;
    it is stored in the payload header for this purpose.  Big-endian fixed-width
    conversion preserves leading zero bytes (e.g. b"\\x00\\xA7" ≠ b"\\xA7").
    """
    value = 0
    for d in digits:
        value = value * n + d
    try:
        return value.to_bytes(num_bytes, "big")
    except OverflowError:
        raise ValueError(
            f"Decoded value overflows {num_bytes} bytes — "
            "data may be corrupted or num_bytes is incorrect."
        )


# =============================================================================
# §4  UNICODE ALPHABETS — Validated tier-based profiles
# =============================================================================
#
#  Source: validated_alphabets.py, generated by unicode_compat.py
#  Every candidate passed all 13 automated Python-level checks.
#  Tier classification is based on Unicode semantics + known cross-platform
#  behaviour (see compat_report.txt for the full per-character breakdown).
#
#  Tier 1  RELIABLE     (11 chars)  Core zero-width / invisible format chars.
#                                   Universally supported across all environments.
#  Tier 2  GOOD         (44 chars)  Directional, deprecated-format, script-filler,
#                                   and BMP variation selectors.  Work in Python
#                                   and most environments but have known caveats.
#  Tier 3  EXPERIMENTAL(354 chars)  Unicode tag characters and Variation Selector
#                                   Supplement (supplementary plane).  Less portable.
#
#  Profile assignments  (chars with tier ≤ threshold are included)
#  ─────────────────────────────────────────────────────────────────
#  PROFILE_SAFE     (0)   11 chars  Tier ≤ 1   3.46 bits/sym   T1 only
#  PROFILE_EXTENDED (1)   55 chars  Tier ≤ 2   5.78 bits/sym   T1 + T2
#  PROFILE_MAX      (2)  409 chars  Tier ≤ 3   8.68 bits/sym   T1 + T2 + T3 ⚠
#
#  ⚠ PROFILE_MAX is EXPERIMENTAL.  Automated tests pass but cross-platform
#    manual tests (clipboard, Windows Notepad, macOS TextEdit, browsers,
#    Android messaging) are required before production use.  See manual_tests.txt.
#  ⚠ U+3164 (HANGUL FILLER) and U+FFA0 (HALFWIDTH HANGUL FILLER) are in
#    EXTENDED/MAX but score 11/13 on automated tests: they collapse under NFKC
#    and NFKD normalization to U+1160.  Avoid EXTENDED/MAX in environments that
#    apply compatibility normalization (some email/messaging systems do this).
#
#  The key permutes the character ORDER (Fisher-Yakes), but never changes which
#  characters BELONG to a profile — that is determined by the tier system above.
#

# ── Tier constants ────────────────────────────────────────────────────────────
TIER_RELIABLE     = 1
TIER_GOOD         = 2
TIER_EXPERIMENTAL = 3

TIER_NAMES: dict = {
    TIER_RELIABLE:     "RELIABLE",
    TIER_GOOD:         "GOOD",
    TIER_EXPERIMENTAL: "EXPERIMENTAL",
}

# ── Profile IDs (preserved from V2 for payload header compatibility) ──────────
PROFILE_SAFE     = 0
PROFILE_EXTENDED = 1
PROFILE_MAX      = 2

PROFILE_NAMES: dict = {
    PROFILE_SAFE:     "SAFE",
    PROFILE_EXTENDED: "EXTENDED",
    PROFILE_MAX:      "MAX",
}

PROFILE_STATUS: dict = {
    PROFILE_SAFE:     "RELIABLE    — Tier 1 chars; universally supported",
    PROFILE_EXTENDED: "GOOD        — Tier 1+2; most environments",
    PROFILE_MAX:      "EXPERIMENTAL— Tier 1+2+3; manual cross-platform tests pending",
}

# ── Tier 1 RELIABLE: 11 chars ─────────────────────────────────────────────────
_SAFE_CHARS: list = [
    "\u00AD",  # U+00AD  SOFT HYPHEN                        T1
    "\u034F",  # U+034F  COMBINING GRAPHEME JOINER          T1
    "\u200B",  # U+200B  ZERO WIDTH SPACE                   T1
    "\u200C",  # U+200C  ZERO WIDTH NON-JOINER              T1
    "\u200D",  # U+200D  ZERO WIDTH JOINER                  T1
    "\u2060",  # U+2060  WORD JOINER                        T1
    "\u2061",  # U+2061  FUNCTION APPLICATION               T1
    "\u2062",  # U+2062  INVISIBLE TIMES                    T1
    "\u2063",  # U+2063  INVISIBLE SEPARATOR                T1
    "\u2064",  # U+2064  INVISIBLE PLUS                     T1
    "\uFEFF",  # U+FEFF  ZERO WIDTH NO-BREAK SPACE          T1
]

# ── Tier 1+2 GOOD: 55 chars ───────────────────────────────────────────────────
_EXTENDED_CHARS: list = [
    "\u00AD",  # U+00AD  SOFT HYPHEN                                T1
    "\u034F",  # U+034F  COMBINING GRAPHEME JOINER                  T1
    "\u115F",  # U+115F  HANGUL CHOSEONG FILLER                     T2
    "\u1160",  # U+1160  HANGUL JUNGSEONG FILLER                    T2
    "\u17B4",  # U+17B4  KHMER VOWEL INHERENT AQ                    T2
    "\u17B5",  # U+17B5  KHMER VOWEL INHERENT AA                    T2
    "\u180B",  # U+180B  MONGOLIAN FREE VARIATION SELECTOR ONE      T2
    "\u180C",  # U+180C  MONGOLIAN FREE VARIATION SELECTOR TWO      T2
    "\u180D",  # U+180D  MONGOLIAN FREE VARIATION SELECTOR THREE    T2
    "\u180E",  # U+180E  MONGOLIAN VOWEL SEPARATOR                  T2
    "\u200B",  # U+200B  ZERO WIDTH SPACE                           T1
    "\u200C",  # U+200C  ZERO WIDTH NON-JOINER                      T1
    "\u200D",  # U+200D  ZERO WIDTH JOINER                          T1
    "\u200E",  # U+200E  LEFT-TO-RIGHT MARK                         T2
    "\u200F",  # U+200F  RIGHT-TO-LEFT MARK                         T2
    "\u061C",  # U+061C  ARABIC LETTER MARK                         T2
    "\u202A",  # U+202A  LEFT-TO-RIGHT EMBEDDING                    T2
    "\u202B",  # U+202B  RIGHT-TO-LEFT EMBEDDING                    T2
    "\u202C",  # U+202C  POP DIRECTIONAL FORMATTING                 T2
    "\u202D",  # U+202D  LEFT-TO-RIGHT OVERRIDE                     T2
    "\u202E",  # U+202E  RIGHT-TO-LEFT OVERRIDE                     T2
    "\u2060",  # U+2060  WORD JOINER                                T1
    "\u2061",  # U+2061  FUNCTION APPLICATION                       T1
    "\u2062",  # U+2062  INVISIBLE TIMES                            T1
    "\u2063",  # U+2063  INVISIBLE SEPARATOR                        T1
    "\u2064",  # U+2064  INVISIBLE PLUS                             T1
    "\u2066",  # U+2066  LEFT-TO-RIGHT ISOLATE                      T2
    "\u2067",  # U+2067  RIGHT-TO-LEFT ISOLATE                      T2
    "\u2068",  # U+2068  FIRST STRONG ISOLATE                       T2
    "\u2069",  # U+2069  POP DIRECTIONAL ISOLATE                    T2
    "\u206A",  # U+206A  INHIBIT SYMMETRIC SWAPPING                 T2
    "\u206B",  # U+206B  ACTIVATE SYMMETRIC SWAPPING                T2
    "\u206C",  # U+206C  INHIBIT ARABIC FORM SHAPING                T2
    "\u206D",  # U+206D  ACTIVATE ARABIC FORM SHAPING               T2
    "\u206E",  # U+206E  NATIONAL DIGIT SHAPES                      T2
    "\u206F",  # U+206F  NOMINAL DIGIT SHAPES                       T2
    "\u3164",  # U+3164  HANGUL FILLER                              T2
    "\uFEFF",  # U+FEFF  ZERO WIDTH NO-BREAK SPACE                  T1
    "\uFE00",  # U+FE00  VARIATION SELECTOR-1                       T2
    "\uFE01",  # U+FE01  VARIATION SELECTOR-2                       T2
    "\uFE02",  # U+FE02  VARIATION SELECTOR-3                       T2
    "\uFE03",  # U+FE03  VARIATION SELECTOR-4                       T2
    "\uFE04",  # U+FE04  VARIATION SELECTOR-5                       T2
    "\uFE05",  # U+FE05  VARIATION SELECTOR-6                       T2
    "\uFE06",  # U+FE06  VARIATION SELECTOR-7                       T2
    "\uFE07",  # U+FE07  VARIATION SELECTOR-8                       T2
    "\uFE08",  # U+FE08  VARIATION SELECTOR-9                       T2
    "\uFE09",  # U+FE09  VARIATION SELECTOR-10                      T2
    "\uFE0A",  # U+FE0A  VARIATION SELECTOR-11                      T2
    "\uFE0B",  # U+FE0B  VARIATION SELECTOR-12                      T2
    "\uFE0C",  # U+FE0C  VARIATION SELECTOR-13                      T2
    "\uFE0D",  # U+FE0D  VARIATION SELECTOR-14                      T2
    "\uFE0E",  # U+FE0E  VARIATION SELECTOR-15                      T2
    "\uFE0F",  # U+FE0F  VARIATION SELECTOR-16                      T2
    "\uFFA0",  # U+FFA0  HALFWIDTH HANGUL FILLER                    T2
]

# ── Tier 1+2+3 EXPERIMENTAL: 409 chars ───────────────────────────────────────
#  Source: validated_alphabets.py  ·  ⚠ pending cross-platform manual testing
_MAX_CHARS: list = [
    "\u00AD",       # U+00AD    SOFT HYPHEN                        T1
    "\u034F",       # U+034F    COMBINING GRAPHEME JOINER          T1
    "\u115F",       # U+115F    HANGUL CHOSEONG FILLER             T2
    "\u1160",       # U+1160    HANGUL JUNGSEONG FILLER            T2
    "\u17B4",       # U+17B4    KHMER VOWEL INHERENT AQ            T2
    "\u17B5",       # U+17B5    KHMER VOWEL INHERENT AA            T2
    "\u180B",       # U+180B    MONGOLIAN FREE VAR SEL ONE         T2
    "\u180C",       # U+180C    MONGOLIAN FREE VAR SEL TWO         T2
    "\u180D",       # U+180D    MONGOLIAN FREE VAR SEL THREE       T2
    "\u180E",       # U+180E    MONGOLIAN VOWEL SEPARATOR          T2
    "\u200B",       # U+200B    ZERO WIDTH SPACE                   T1
    "\u200C",       # U+200C    ZERO WIDTH NON-JOINER              T1
    "\u200D",       # U+200D    ZERO WIDTH JOINER                  T1
    "\u200E",       # U+200E    LEFT-TO-RIGHT MARK                 T2
    "\u200F",       # U+200F    RIGHT-TO-LEFT MARK                 T2
    "\u061C",       # U+061C    ARABIC LETTER MARK                 T2
    "\u202A",       # U+202A    LEFT-TO-RIGHT EMBEDDING            T2
    "\u202B",       # U+202B    RIGHT-TO-LEFT EMBEDDING            T2
    "\u202C",       # U+202C    POP DIRECTIONAL FORMATTING         T2
    "\u202D",       # U+202D    LEFT-TO-RIGHT OVERRIDE             T2
    "\u202E",       # U+202E    RIGHT-TO-LEFT OVERRIDE             T2
    "\u2060",       # U+2060    WORD JOINER                        T1
    "\u2061",       # U+2061    FUNCTION APPLICATION               T1
    "\u2062",       # U+2062    INVISIBLE TIMES                    T1
    "\u2063",       # U+2063    INVISIBLE SEPARATOR                T1
    "\u2064",       # U+2064    INVISIBLE PLUS                     T1
    "\u2066",       # U+2066    LEFT-TO-RIGHT ISOLATE              T2
    "\u2067",       # U+2067    RIGHT-TO-LEFT ISOLATE              T2
    "\u2068",       # U+2068    FIRST STRONG ISOLATE               T2
    "\u2069",       # U+2069    POP DIRECTIONAL ISOLATE            T2
    "\u206A",       # U+206A    INHIBIT SYMMETRIC SWAPPING         T2
    "\u206B",       # U+206B    ACTIVATE SYMMETRIC SWAPPING        T2
    "\u206C",       # U+206C    INHIBIT ARABIC FORM SHAPING        T2
    "\u206D",       # U+206D    ACTIVATE ARABIC FORM SHAPING       T2
    "\u206E",       # U+206E    NATIONAL DIGIT SHAPES              T2
    "\u206F",       # U+206F    NOMINAL DIGIT SHAPES               T2
    "\u3164",       # U+3164    HANGUL FILLER                      T2
    "\uFEFF",       # U+FEFF    ZERO WIDTH NO-BREAK SPACE          T1
    "\uFE00",       # U+FE00    VARIATION SELECTOR-1               T2
    "\uFE01",       # U+FE01    VARIATION SELECTOR-2               T2
    "\uFE02",       # U+FE02    VARIATION SELECTOR-3               T2
    "\uFE03",       # U+FE03    VARIATION SELECTOR-4               T2
    "\uFE04",       # U+FE04    VARIATION SELECTOR-5               T2
    "\uFE05",       # U+FE05    VARIATION SELECTOR-6               T2
    "\uFE06",       # U+FE06    VARIATION SELECTOR-7               T2
    "\uFE07",       # U+FE07    VARIATION SELECTOR-8               T2
    "\uFE08",       # U+FE08    VARIATION SELECTOR-9               T2
    "\uFE09",       # U+FE09    VARIATION SELECTOR-10              T2
    "\uFE0A",       # U+FE0A    VARIATION SELECTOR-11              T2
    "\uFE0B",       # U+FE0B    VARIATION SELECTOR-12              T2
    "\uFE0C",       # U+FE0C    VARIATION SELECTOR-13              T2
    "\uFE0D",       # U+FE0D    VARIATION SELECTOR-14              T2
    "\uFE0E",       # U+FE0E    VARIATION SELECTOR-15              T2
    "\uFE0F",       # U+FE0F    VARIATION SELECTOR-16              T2
    "\uFFA0",       # U+FFA0    HALFWIDTH HANGUL FILLER            T2
    # ── Tier 3: Tag chars (U+E0001, U+E0020–U+E007F) ──────────────────────
    "\U000E0001",   # LANGUAGE TAG                                  T3
    "\U000E0020",   # TAG SPACE                                     T3
    "\U000E0021",   # TAG EXCLAMATION MARK                          T3
    "\U000E0022",   # TAG QUOTATION MARK                            T3
    "\U000E0023",   # TAG NUMBER SIGN                               T3
    "\U000E0024",   # TAG DOLLAR SIGN                               T3
    "\U000E0025",   # TAG PERCENT SIGN                              T3
    "\U000E0026",   # TAG AMPERSAND                                 T3
    "\U000E0027",   # TAG APOSTROPHE                                T3
    "\U000E0028",   # TAG LEFT PARENTHESIS                          T3
    "\U000E0029",   # TAG RIGHT PARENTHESIS                         T3
    "\U000E002A",   # TAG ASTERISK                                  T3
    "\U000E002B",   # TAG PLUS SIGN                                 T3
    "\U000E002C",   # TAG COMMA                                     T3
    "\U000E002D",   # TAG HYPHEN-MINUS                              T3
    "\U000E002E",   # TAG FULL STOP                                 T3
    "\U000E002F",   # TAG SOLIDUS                                   T3
    "\U000E0030",   # TAG DIGIT ZERO                                T3
    "\U000E0031",   # TAG DIGIT ONE                                 T3
    "\U000E0032",   # TAG DIGIT TWO                                 T3
    "\U000E0033",   # TAG DIGIT THREE                               T3
    "\U000E0034",   # TAG DIGIT FOUR                                T3
    "\U000E0035",   # TAG DIGIT FIVE                                T3
    "\U000E0036",   # TAG DIGIT SIX                                 T3
    "\U000E0037",   # TAG DIGIT SEVEN                               T3
    "\U000E0038",   # TAG DIGIT EIGHT                               T3
    "\U000E0039",   # TAG DIGIT NINE                                T3
    "\U000E003A",   # TAG COLON                                     T3
    "\U000E003B",   # TAG SEMICOLON                                 T3
    "\U000E003C",   # TAG LESS-THAN SIGN                            T3
    "\U000E003D",   # TAG EQUALS SIGN                               T3
    "\U000E003E",   # TAG GREATER-THAN SIGN                         T3
    "\U000E003F",   # TAG QUESTION MARK                             T3
    "\U000E0040",   # TAG COMMERCIAL AT                             T3
    "\U000E0041",   # TAG LATIN CAPITAL LETTER A                    T3
    "\U000E0042",   # TAG LATIN CAPITAL LETTER B                    T3
    "\U000E0043",   # TAG LATIN CAPITAL LETTER C                    T3
    "\U000E0044",   # TAG LATIN CAPITAL LETTER D                    T3
    "\U000E0045",   # TAG LATIN CAPITAL LETTER E                    T3
    "\U000E0046",   # TAG LATIN CAPITAL LETTER F                    T3
    "\U000E0047",   # TAG LATIN CAPITAL LETTER G                    T3
    "\U000E0048",   # TAG LATIN CAPITAL LETTER H                    T3
    "\U000E0049",   # TAG LATIN CAPITAL LETTER I                    T3
    "\U000E004A",   # TAG LATIN CAPITAL LETTER J                    T3
    "\U000E004B",   # TAG LATIN CAPITAL LETTER K                    T3
    "\U000E004C",   # TAG LATIN CAPITAL LETTER L                    T3
    "\U000E004D",   # TAG LATIN CAPITAL LETTER M                    T3
    "\U000E004E",   # TAG LATIN CAPITAL LETTER N                    T3
    "\U000E004F",   # TAG LATIN CAPITAL LETTER O                    T3
    "\U000E0050",   # TAG LATIN CAPITAL LETTER P                    T3
    "\U000E0051",   # TAG LATIN CAPITAL LETTER Q                    T3
    "\U000E0052",   # TAG LATIN CAPITAL LETTER R                    T3
    "\U000E0053",   # TAG LATIN CAPITAL LETTER S                    T3
    "\U000E0054",   # TAG LATIN CAPITAL LETTER T                    T3
    "\U000E0055",   # TAG LATIN CAPITAL LETTER U                    T3
    "\U000E0056",   # TAG LATIN CAPITAL LETTER V                    T3
    "\U000E0057",   # TAG LATIN CAPITAL LETTER W                    T3
    "\U000E0058",   # TAG LATIN CAPITAL LETTER X                    T3
    "\U000E0059",   # TAG LATIN CAPITAL LETTER Y                    T3
    "\U000E005A",   # TAG LATIN CAPITAL LETTER Z                    T3
    "\U000E005B",   # TAG LEFT SQUARE BRACKET                       T3
    "\U000E005C",   # TAG REVERSE SOLIDUS                           T3
    "\U000E005D",   # TAG RIGHT SQUARE BRACKET                      T3
    "\U000E005E",   # TAG CIRCUMFLEX ACCENT                         T3
    "\U000E005F",   # TAG LOW LINE                                  T3
    "\U000E0060",   # TAG GRAVE ACCENT                              T3
    "\U000E0061",   # TAG LATIN SMALL LETTER A                      T3
    "\U000E0062",   # TAG LATIN SMALL LETTER B                      T3
    "\U000E0063",   # TAG LATIN SMALL LETTER C                      T3
    "\U000E0064",   # TAG LATIN SMALL LETTER D                      T3
    "\U000E0065",   # TAG LATIN SMALL LETTER E                      T3
    "\U000E0066",   # TAG LATIN SMALL LETTER F                      T3
    "\U000E0067",   # TAG LATIN SMALL LETTER G                      T3
    "\U000E0068",   # TAG LATIN SMALL LETTER H                      T3
    "\U000E0069",   # TAG LATIN SMALL LETTER I                      T3
    "\U000E006A",   # TAG LATIN SMALL LETTER J                      T3
    "\U000E006B",   # TAG LATIN SMALL LETTER K                      T3
    "\U000E006C",   # TAG LATIN SMALL LETTER L                      T3
    "\U000E006D",   # TAG LATIN SMALL LETTER M                      T3
    "\U000E006E",   # TAG LATIN SMALL LETTER N                      T3
    "\U000E006F",   # TAG LATIN SMALL LETTER O                      T3
    "\U000E0070",   # TAG LATIN SMALL LETTER P                      T3
    "\U000E0071",   # TAG LATIN SMALL LETTER Q                      T3
    "\U000E0072",   # TAG LATIN SMALL LETTER R                      T3
    "\U000E0073",   # TAG LATIN SMALL LETTER S                      T3
    "\U000E0074",   # TAG LATIN SMALL LETTER T                      T3
    "\U000E0075",   # TAG LATIN SMALL LETTER U                      T3
    "\U000E0076",   # TAG LATIN SMALL LETTER V                      T3
    "\U000E0077",   # TAG LATIN SMALL LETTER W                      T3
    "\U000E0078",   # TAG LATIN SMALL LETTER X                      T3
    "\U000E0079",   # TAG LATIN SMALL LETTER Y                      T3
    "\U000E007A",   # TAG LATIN SMALL LETTER Z                      T3
    "\U000E007B",   # TAG LEFT CURLY BRACKET                        T3
    "\U000E007C",   # TAG VERTICAL LINE                             T3
    "\U000E007D",   # TAG RIGHT CURLY BRACKET                       T3
    "\U000E007E",   # TAG TILDE                                     T3
    "\U000E007F",   # CANCEL TAG                                    T3
    # ── Tier 3: Variation Selector Supplement (U+E0100–U+E0200) ───────────
    "\U000E0100",   # VARIATION SELECTOR-17                         T3
    "\U000E0101",   # VARIATION SELECTOR-18                         T3
    "\U000E0102",   # VARIATION SELECTOR-19                         T3
    "\U000E0103",   # VARIATION SELECTOR-20                         T3
    "\U000E0104",   # VARIATION SELECTOR-21                         T3
    "\U000E0105",   # VARIATION SELECTOR-22                         T3
    "\U000E0106",   # VARIATION SELECTOR-23                         T3
    "\U000E0107",   # VARIATION SELECTOR-24                         T3
    "\U000E0108",   # VARIATION SELECTOR-25                         T3
    "\U000E0109",   # VARIATION SELECTOR-26                         T3
    "\U000E010A",   # VARIATION SELECTOR-27                         T3
    "\U000E010B",   # VARIATION SELECTOR-28                         T3
    "\U000E010C",   # VARIATION SELECTOR-29                         T3
    "\U000E010D",   # VARIATION SELECTOR-30                         T3
    "\U000E010E",   # VARIATION SELECTOR-31                         T3
    "\U000E010F",   # VARIATION SELECTOR-32                         T3
    "\U000E0110",   # VARIATION SELECTOR-33                         T3
    "\U000E0111",   # VARIATION SELECTOR-34                         T3
    "\U000E0112",   # VARIATION SELECTOR-35                         T3
    "\U000E0113",   # VARIATION SELECTOR-36                         T3
    "\U000E0114",   # VARIATION SELECTOR-37                         T3
    "\U000E0115",   # VARIATION SELECTOR-38                         T3
    "\U000E0116",   # VARIATION SELECTOR-39                         T3
    "\U000E0117",   # VARIATION SELECTOR-40                         T3
    "\U000E0118",   # VARIATION SELECTOR-41                         T3
    "\U000E0119",   # VARIATION SELECTOR-42                         T3
    "\U000E011A",   # VARIATION SELECTOR-43                         T3
    "\U000E011B",   # VARIATION SELECTOR-44                         T3
    "\U000E011C",   # VARIATION SELECTOR-45                         T3
    "\U000E011D",   # VARIATION SELECTOR-46                         T3
    "\U000E011E",   # VARIATION SELECTOR-47                         T3
    "\U000E011F",   # VARIATION SELECTOR-48                         T3
    "\U000E0120",   # VARIATION SELECTOR-49                         T3
    "\U000E0121",   # VARIATION SELECTOR-50                         T3
    "\U000E0122",   # VARIATION SELECTOR-51                         T3
    "\U000E0123",   # VARIATION SELECTOR-52                         T3
    "\U000E0124",   # VARIATION SELECTOR-53                         T3
    "\U000E0125",   # VARIATION SELECTOR-54                         T3
    "\U000E0126",   # VARIATION SELECTOR-55                         T3
    "\U000E0127",   # VARIATION SELECTOR-56                         T3
    "\U000E0128",   # VARIATION SELECTOR-57                         T3
    "\U000E0129",   # VARIATION SELECTOR-58                         T3
    "\U000E012A",   # VARIATION SELECTOR-59                         T3
    "\U000E012B",   # VARIATION SELECTOR-60                         T3
    "\U000E012C",   # VARIATION SELECTOR-61                         T3
    "\U000E012D",   # VARIATION SELECTOR-62                         T3
    "\U000E012E",   # VARIATION SELECTOR-63                         T3
    "\U000E012F",   # VARIATION SELECTOR-64                         T3
    "\U000E0130",   # VARIATION SELECTOR-65                         T3
    "\U000E0131",   # VARIATION SELECTOR-66                         T3
    "\U000E0132",   # VARIATION SELECTOR-67                         T3
    "\U000E0133",   # VARIATION SELECTOR-68                         T3
    "\U000E0134",   # VARIATION SELECTOR-69                         T3
    "\U000E0135",   # VARIATION SELECTOR-70                         T3
    "\U000E0136",   # VARIATION SELECTOR-71                         T3
    "\U000E0137",   # VARIATION SELECTOR-72                         T3
    "\U000E0138",   # VARIATION SELECTOR-73                         T3
    "\U000E0139",   # VARIATION SELECTOR-74                         T3
    "\U000E013A",   # VARIATION SELECTOR-75                         T3
    "\U000E013B",   # VARIATION SELECTOR-76                         T3
    "\U000E013C",   # VARIATION SELECTOR-77                         T3
    "\U000E013D",   # VARIATION SELECTOR-78                         T3
    "\U000E013E",   # VARIATION SELECTOR-79                         T3
    "\U000E013F",   # VARIATION SELECTOR-80                         T3
    "\U000E0140",   # VARIATION SELECTOR-81                         T3
    "\U000E0141",   # VARIATION SELECTOR-82                         T3
    "\U000E0142",   # VARIATION SELECTOR-83                         T3
    "\U000E0143",   # VARIATION SELECTOR-84                         T3
    "\U000E0144",   # VARIATION SELECTOR-85                         T3
    "\U000E0145",   # VARIATION SELECTOR-86                         T3
    "\U000E0146",   # VARIATION SELECTOR-87                         T3
    "\U000E0147",   # VARIATION SELECTOR-88                         T3
    "\U000E0148",   # VARIATION SELECTOR-89                         T3
    "\U000E0149",   # VARIATION SELECTOR-90                         T3
    "\U000E014A",   # VARIATION SELECTOR-91                         T3
    "\U000E014B",   # VARIATION SELECTOR-92                         T3
    "\U000E014C",   # VARIATION SELECTOR-93                         T3
    "\U000E014D",   # VARIATION SELECTOR-94                         T3
    "\U000E014E",   # VARIATION SELECTOR-95                         T3
    "\U000E014F",   # VARIATION SELECTOR-96                         T3
    "\U000E0150",   # VARIATION SELECTOR-97                         T3
    "\U000E0151",   # VARIATION SELECTOR-98                         T3
    "\U000E0152",   # VARIATION SELECTOR-99                         T3
    "\U000E0153",   # VARIATION SELECTOR-100                        T3
    "\U000E0154",   # VARIATION SELECTOR-101                        T3
    "\U000E0155",   # VARIATION SELECTOR-102                        T3
    "\U000E0156",   # VARIATION SELECTOR-103                        T3
    "\U000E0157",   # VARIATION SELECTOR-104                        T3
    "\U000E0158",   # VARIATION SELECTOR-105                        T3
    "\U000E0159",   # VARIATION SELECTOR-106                        T3
    "\U000E015A",   # VARIATION SELECTOR-107                        T3
    "\U000E015B",   # VARIATION SELECTOR-108                        T3
    "\U000E015C",   # VARIATION SELECTOR-109                        T3
    "\U000E015D",   # VARIATION SELECTOR-110                        T3
    "\U000E015E",   # VARIATION SELECTOR-111                        T3
    "\U000E015F",   # VARIATION SELECTOR-112                        T3
    "\U000E0160",   # VARIATION SELECTOR-113                        T3
    "\U000E0161",   # VARIATION SELECTOR-114                        T3
    "\U000E0162",   # VARIATION SELECTOR-115                        T3
    "\U000E0163",   # VARIATION SELECTOR-116                        T3
    "\U000E0164",   # VARIATION SELECTOR-117                        T3
    "\U000E0165",   # VARIATION SELECTOR-118                        T3
    "\U000E0166",   # VARIATION SELECTOR-119                        T3
    "\U000E0167",   # VARIATION SELECTOR-120                        T3
    "\U000E0168",   # VARIATION SELECTOR-121                        T3
    "\U000E0169",   # VARIATION SELECTOR-122                        T3
    "\U000E016A",   # VARIATION SELECTOR-123                        T3
    "\U000E016B",   # VARIATION SELECTOR-124                        T3
    "\U000E016C",   # VARIATION SELECTOR-125                        T3
    "\U000E016D",   # VARIATION SELECTOR-126                        T3
    "\U000E016E",   # VARIATION SELECTOR-127                        T3
    "\U000E016F",   # VARIATION SELECTOR-128                        T3
    "\U000E0170",   # VARIATION SELECTOR-129                        T3
    "\U000E0171",   # VARIATION SELECTOR-130                        T3
    "\U000E0172",   # VARIATION SELECTOR-131                        T3
    "\U000E0173",   # VARIATION SELECTOR-132                        T3
    "\U000E0174",   # VARIATION SELECTOR-133                        T3
    "\U000E0175",   # VARIATION SELECTOR-134                        T3
    "\U000E0176",   # VARIATION SELECTOR-135                        T3
    "\U000E0177",   # VARIATION SELECTOR-136                        T3
    "\U000E0178",   # VARIATION SELECTOR-137                        T3
    "\U000E0179",   # VARIATION SELECTOR-138                        T3
    "\U000E017A",   # VARIATION SELECTOR-139                        T3
    "\U000E017B",   # VARIATION SELECTOR-140                        T3
    "\U000E017C",   # VARIATION SELECTOR-141                        T3
    "\U000E017D",   # VARIATION SELECTOR-142                        T3
    "\U000E017E",   # VARIATION SELECTOR-143                        T3
    "\U000E017F",   # VARIATION SELECTOR-144                        T3
    "\U000E0180",   # VARIATION SELECTOR-145                        T3
    "\U000E0181",   # VARIATION SELECTOR-146                        T3
    "\U000E0182",   # VARIATION SELECTOR-147                        T3
    "\U000E0183",   # VARIATION SELECTOR-148                        T3
    "\U000E0184",   # VARIATION SELECTOR-149                        T3
    "\U000E0185",   # VARIATION SELECTOR-150                        T3
    "\U000E0186",   # VARIATION SELECTOR-151                        T3
    "\U000E0187",   # VARIATION SELECTOR-152                        T3
    "\U000E0188",   # VARIATION SELECTOR-153                        T3
    "\U000E0189",   # VARIATION SELECTOR-154                        T3
    "\U000E018A",   # VARIATION SELECTOR-155                        T3
    "\U000E018B",   # VARIATION SELECTOR-156                        T3
    "\U000E018C",   # VARIATION SELECTOR-157                        T3
    "\U000E018D",   # VARIATION SELECTOR-158                        T3
    "\U000E018E",   # VARIATION SELECTOR-159                        T3
    "\U000E018F",   # VARIATION SELECTOR-160                        T3
    "\U000E0190",   # VARIATION SELECTOR-161                        T3
    "\U000E0191",   # VARIATION SELECTOR-162                        T3
    "\U000E0192",   # VARIATION SELECTOR-163                        T3
    "\U000E0193",   # VARIATION SELECTOR-164                        T3
    "\U000E0194",   # VARIATION SELECTOR-165                        T3
    "\U000E0195",   # VARIATION SELECTOR-166                        T3
    "\U000E0196",   # VARIATION SELECTOR-167                        T3
    "\U000E0197",   # VARIATION SELECTOR-168                        T3
    "\U000E0198",   # VARIATION SELECTOR-169                        T3
    "\U000E0199",   # VARIATION SELECTOR-170                        T3
    "\U000E019A",   # VARIATION SELECTOR-171                        T3
    "\U000E019B",   # VARIATION SELECTOR-172                        T3
    "\U000E019C",   # VARIATION SELECTOR-173                        T3
    "\U000E019D",   # VARIATION SELECTOR-174                        T3
    "\U000E019E",   # VARIATION SELECTOR-175                        T3
    "\U000E019F",   # VARIATION SELECTOR-176                        T3
    "\U000E01A0",   # VARIATION SELECTOR-177                        T3
    "\U000E01A1",   # VARIATION SELECTOR-178                        T3
    "\U000E01A2",   # VARIATION SELECTOR-179                        T3
    "\U000E01A3",   # VARIATION SELECTOR-180                        T3
    "\U000E01A4",   # VARIATION SELECTOR-181                        T3
    "\U000E01A5",   # VARIATION SELECTOR-182                        T3
    "\U000E01A6",   # VARIATION SELECTOR-183                        T3
    "\U000E01A7",   # VARIATION SELECTOR-184                        T3
    "\U000E01A8",   # VARIATION SELECTOR-185                        T3
    "\U000E01A9",   # VARIATION SELECTOR-186                        T3
    "\U000E01AA",   # VARIATION SELECTOR-187                        T3
    "\U000E01AB",   # VARIATION SELECTOR-188                        T3
    "\U000E01AC",   # VARIATION SELECTOR-189                        T3
    "\U000E01AD",   # VARIATION SELECTOR-190                        T3
    "\U000E01AE",   # VARIATION SELECTOR-191                        T3
    "\U000E01AF",   # VARIATION SELECTOR-192                        T3
    "\U000E01B0",   # VARIATION SELECTOR-193                        T3
    "\U000E01B1",   # VARIATION SELECTOR-194                        T3
    "\U000E01B2",   # VARIATION SELECTOR-195                        T3
    "\U000E01B3",   # VARIATION SELECTOR-196                        T3
    "\U000E01B4",   # VARIATION SELECTOR-197                        T3
    "\U000E01B5",   # VARIATION SELECTOR-198                        T3
    "\U000E01B6",   # VARIATION SELECTOR-199                        T3
    "\U000E01B7",   # VARIATION SELECTOR-200                        T3
    "\U000E01B8",   # VARIATION SELECTOR-201                        T3
    "\U000E01B9",   # VARIATION SELECTOR-202                        T3
    "\U000E01BA",   # VARIATION SELECTOR-203                        T3
    "\U000E01BB",   # VARIATION SELECTOR-204                        T3
    "\U000E01BC",   # VARIATION SELECTOR-205                        T3
    "\U000E01BD",   # VARIATION SELECTOR-206                        T3
    "\U000E01BE",   # VARIATION SELECTOR-207                        T3
    "\U000E01BF",   # VARIATION SELECTOR-208                        T3
    "\U000E01C0",   # VARIATION SELECTOR-209                        T3
    "\U000E01C1",   # VARIATION SELECTOR-210                        T3
    "\U000E01C2",   # VARIATION SELECTOR-211                        T3
    "\U000E01C3",   # VARIATION SELECTOR-212                        T3
    "\U000E01C4",   # VARIATION SELECTOR-213                        T3
    "\U000E01C5",   # VARIATION SELECTOR-214                        T3
    "\U000E01C6",   # VARIATION SELECTOR-215                        T3
    "\U000E01C7",   # VARIATION SELECTOR-216                        T3
    "\U000E01C8",   # VARIATION SELECTOR-217                        T3
    "\U000E01C9",   # VARIATION SELECTOR-218                        T3
    "\U000E01CA",   # VARIATION SELECTOR-219                        T3
    "\U000E01CB",   # VARIATION SELECTOR-220                        T3
    "\U000E01CC",   # VARIATION SELECTOR-221                        T3
    "\U000E01CD",   # VARIATION SELECTOR-222                        T3
    "\U000E01CE",   # VARIATION SELECTOR-223                        T3
    "\U000E01CF",   # VARIATION SELECTOR-224                        T3
    "\U000E01D0",   # VARIATION SELECTOR-225                        T3
    "\U000E01D1",   # VARIATION SELECTOR-226                        T3
    "\U000E01D2",   # VARIATION SELECTOR-227                        T3
    "\U000E01D3",   # VARIATION SELECTOR-228                        T3
    "\U000E01D4",   # VARIATION SELECTOR-229                        T3
    "\U000E01D5",   # VARIATION SELECTOR-230                        T3
    "\U000E01D6",   # VARIATION SELECTOR-231                        T3
    "\U000E01D7",   # VARIATION SELECTOR-232                        T3
    "\U000E01D8",   # VARIATION SELECTOR-233                        T3
    "\U000E01D9",   # VARIATION SELECTOR-234                        T3
    "\U000E01DA",   # VARIATION SELECTOR-235                        T3
    "\U000E01DB",   # VARIATION SELECTOR-236                        T3
    "\U000E01DC",   # VARIATION SELECTOR-237                        T3
    "\U000E01DD",   # VARIATION SELECTOR-238                        T3
    "\U000E01DE",   # VARIATION SELECTOR-239                        T3
    "\U000E01DF",   # VARIATION SELECTOR-240                        T3
    "\U000E01E0",   # VARIATION SELECTOR-241                        T3
    "\U000E01E1",   # VARIATION SELECTOR-242                        T3
    "\U000E01E2",   # VARIATION SELECTOR-243                        T3
    "\U000E01E3",   # VARIATION SELECTOR-244                        T3
    "\U000E01E4",   # VARIATION SELECTOR-245                        T3
    "\U000E01E5",   # VARIATION SELECTOR-246                        T3
    "\U000E01E6",   # VARIATION SELECTOR-247                        T3
    "\U000E01E7",   # VARIATION SELECTOR-248                        T3
    "\U000E01E8",   # VARIATION SELECTOR-249                        T3
    "\U000E01E9",   # VARIATION SELECTOR-250                        T3
    "\U000E01EA",   # VARIATION SELECTOR-251                        T3
    "\U000E01EB",   # VARIATION SELECTOR-252                        T3
    "\U000E01EC",   # VARIATION SELECTOR-253                        T3
    "\U000E01ED",   # VARIATION SELECTOR-254                        T3
    "\U000E01EE",   # VARIATION SELECTOR-255                        T3
    "\U000E01EF",   # VARIATION SELECTOR-256                        T3
    # ── U+E01F0–U+E0200 deliberately excluded ────────────────────────────
    # These 17 code points lie beyond the official Unicode Variation Selector
    # Supplement block end (U+E01EF).  They are unassigned, have no Unicode
    # name, and were included in the 409-char set by a range-end bug in the
    # original unicode_compat.py (range(0xE0100, 0xE0201) instead of
    # range(0xE0100, 0xE01F0)).  Removing them corrects MAX to 392 chars.
]

# ── Tier lookup (built at load time for Stage 0 testing) ─────────────────────
_safe_set = frozenset(_SAFE_CHARS)
_ext_set  = frozenset(_EXTENDED_CHARS)

def _char_tier(ch: str) -> int:
    """Return the tier (1/2/3) of a stego character."""
    if ch in _safe_set: return TIER_RELIABLE
    if ch in _ext_set:  return TIER_GOOD
    return TIER_EXPERIMENTAL

_CHAR_TIERS: dict = {ch: _char_tier(ch) for ch in _MAX_CHARS}

# ── Profile → character list mapping ─────────────────────────────────────────
_PROFILE_CHARS: dict = {
    PROFILE_SAFE:     _SAFE_CHARS,
    PROFILE_EXTENDED: _EXTENDED_CHARS,
    PROFILE_MAX:      _MAX_CHARS,
}

# Union of all stego characters across all profiles (for extraction / stripping)
_ALL_STEGO_CHARS: frozenset = frozenset(_MAX_CHARS)


def _is_stego(ch: str) -> bool:
    return ch in _ALL_STEGO_CHARS


def _strip_stego(text: str) -> str:
    """Remove every stego invisible character from text."""
    return "".join(ch for ch in text if not _is_stego(ch))


def _get_profile_chars(profile_id: int) -> list:
    if profile_id not in _PROFILE_CHARS:
        raise ValueError(f"Unknown profile_id: {profile_id}")
    return list(_PROFILE_CHARS[profile_id])


def _keyed_alphabet(profile_id: int, password: str) -> list:
    """
    Return the profile's character list permuted deterministically by the key.
    Uses Fisher-Yates with per-index SHA-256 sub-keys for uniform randomness.
    """
    chars = _get_profile_chars(profile_id)
    seed  = hashlib.sha256(b"stego:v2:alpha:" + password.encode()).digest()
    n     = len(chars)
    for i in range(n - 1, 0, -1):
        h = hashlib.sha256(seed + struct.pack(">I", i)).digest()
        j = int.from_bytes(h[:4], "big") % (i + 1)
        chars[i], chars[j] = chars[j], chars[i]
    return chars


def profile_info(profile_id: int) -> dict:
    """Return a summary dict for display."""
    chars = _get_profile_chars(profile_id)
    n     = len(chars)
    bps   = math.log2(n) if n > 1 else 0.0          # theoretical bits/symbol
    return {
        "id":           profile_id,
        "name":         PROFILE_NAMES[profile_id],
        "size":         n,
        "bits_per_sym": round(bps, 3),
    }


# =============================================================================
# §5  BASE-N UNICODE ENCODING / DECODING
# =============================================================================
#
#  Thin wrappers that map between §3's integer digit lists and Unicode strings:
#
#    _encode_base_n : bytes → invisible Unicode string
#                     digit d ∈ [0,N) → alphabet[d] character
#    _decode_base_n : invisible Unicode string → bytes
#                     character → alphabet position → digit → bytes
#
#  All arithmetic correctness lives in §3; these functions only do the
#  alphabet ↔ digit mapping.
#

def _encode_base_n(data: bytes, alphabet: list) -> str:
    """
    Encode arbitrary bytes → invisible Unicode string via base-N integer arithmetic.
    Output length = _num_symbols(len(data), N) characters.
    """
    n = len(alphabet)
    if n < 2:
        raise ValueError("Alphabet must have >= 2 symbols.")
    if not data:
        return ""
    digits = _encode_bytes_to_digits(data, n)
    return "".join(alphabet[d] for d in digits)


def _decode_base_n(symbols: str, alphabet: list, num_bytes: int) -> bytes:
    """
    Decode invisible Unicode string → bytes.
    num_bytes MUST match the value stored in the payload header.
    Characters not in the alphabet are silently skipped (defensive guard).
    """
    char_to_idx = {c: i for i, c in enumerate(alphabet)}
    n           = len(alphabet)
    digits      = [char_to_idx[ch] for ch in symbols if ch in char_to_idx]
    return _decode_digits_to_bytes(digits, n, num_bytes)


# =============================================================================
# §6  BINARY PAYLOAD FORMAT
# =============================================================================
#
#  Layout (all multi-byte integers big-endian):
#
#  ┌────────────────────────────────────────────────────────┐
#  │  MAGIC      4 B    b'STGV'                            │
#  │  VERSION    1 B    currently 2                         │
#  │  FLAGS      1 B    bit 0 = compressed                  │
#  │  PROFILE_ID 1 B    0=SAFE 1=EXTENDED 2=MAX             │
#  │  EXT_LEN    1 B    length of file extension string     │
#  │  EXT        N B    file extension (no dot, e.g. "pdf") │
#  │  CRYPT_LEN  4 B    len(ciphertext) + TAG_LEN           │
#  │  SALT      16 B    KDF salt                            │
#  │  NONCE     12 B    AES-GCM nonce                       │
#  │  CIPHERTEXT ? B    AES-GCM ciphertext                  │
#  │  AUTH_TAG  16 B    AES-GCM authentication tag          │
#  └────────────────────────────────────────────────────────┘
#

_MAGIC   = b"STGV"
_VERSION = 3   # v3: updated Unicode alphabet profiles (11/55/409 vs 10/26/122)


def _build_payload(flags: int, profile_id: int, extension: str,
                   salt: bytes, nonce: bytes,
                   ciphertext: bytes, tag: bytes) -> bytes:
    ext_b     = extension.encode("utf-8")
    crypt_len = len(ciphertext) + _TAG_LEN
    return (
        _MAGIC
        + struct.pack("B", _VERSION)
        + struct.pack("B", flags)
        + struct.pack("B", profile_id)
        + struct.pack("B", len(ext_b))
        + ext_b
        + struct.pack(">I", crypt_len)
        + salt
        + nonce
        + ciphertext
        + tag
    )


def _parse_payload(data: bytes) -> dict:
    """Parse binary payload. Returns all header fields plus ciphertext and tag."""
    off = 0

    magic = data[off:off+4]; off += 4
    if magic != _MAGIC:
        raise ValueError(f"Bad MAGIC: {magic!r}  (wrong password?)")

    ver = data[off]; off += 1
    if ver != _VERSION:
        raise ValueError(f"Unsupported format version {ver}")

    flags      = data[off];    off += 1
    profile_id = data[off];    off += 1
    ext_len    = data[off];    off += 1
    extension  = data[off:off+ext_len].decode("utf-8"); off += ext_len
    crypt_len  = struct.unpack(">I", data[off:off+4])[0]; off += 4
    salt       = data[off:off+_SALT_LEN];   off += _SALT_LEN
    nonce      = data[off:off+_NONCE_LEN];  off += _NONCE_LEN
    ciphertext = data[off:off + crypt_len - _TAG_LEN]
    tag        = data[off + crypt_len - _TAG_LEN : off + crypt_len]

    return {
        "flags":      flags,
        "profile_id": profile_id,
        "extension":  extension,
        "salt":       salt,
        "nonce":      nonce,
        "ciphertext": ciphertext,
        "tag":        tag,
    }


# =============================================================================
# §7  INVISIBLE SYMBOL STREAM: EMBEDDING & EXTRACTION
# =============================================================================
#
#  Stream layout:
#
#  ┌──────────────────────────────────────────────────────────────────┐
#  │  LENGTH PREFIX  (_PREFIX_SYMS symbols, always present)           │
#  │  Encoded with the FIXED, unkeyed SAFE alphabet (10 chars).      │
#  │  Contains: profile_id (1 B) + total_payload_bytes (4 B).        │
#  │  Purpose: bootstrap — decoder learns profile + length before     │
#  │           the key-permuted alphabet is constructed.              │
#  ├──────────────────────────────────────────────────────────────────┤
#  │  MAIN PAYLOAD  (variable number of symbols)                      │
#  │  Encoded with the KEY-PERMUTED alphabet for the declared profile.│
#  │  Contains the full binary_payload bytes.                         │
#  └──────────────────────────────────────────────────────────────────┘
#
#  Both parts are embedded in document order, spread evenly through the
#  cover text at inter-character gap positions.
#

_PREFIX_PAYLOAD_LEN = 5   # 1 byte profile_id + 4 bytes uint32 (total bytes)

# Compute via §3's exact formula  (N=10, L=5  →  13 symbols)
_PREFIX_SYMS: int = _num_symbols(_PREFIX_PAYLOAD_LEN, len(_SAFE_CHARS))


# ── length prefix helpers ─────────────────────────────────────────────────────

def _encode_prefix(profile_id: int, total_bytes: int) -> str:
    """Encode (profile_id, total_bytes) → fixed _PREFIX_SYMS invisible symbols."""
    raw = struct.pack("B", profile_id) + struct.pack(">I", total_bytes)
    s   = _encode_base_n(raw, _SAFE_CHARS)   # unkeyed, always SAFE alphabet
    assert len(s) == _PREFIX_SYMS, (
        f"Prefix symbol count mismatch: got {len(s)}, expected {_PREFIX_SYMS}"
    )
    return s


def _decode_prefix(symbols: str) -> Tuple[int, int]:
    """Decode _PREFIX_SYMS symbols → (profile_id, total_bytes)."""
    raw         = _decode_base_n(symbols, _SAFE_CHARS, _PREFIX_PAYLOAD_LEN)
    profile_id  = raw[0]
    total_bytes = struct.unpack(">I", raw[1:5])[0]
    return profile_id, total_bytes


# ── capacity ──────────────────────────────────────────────────────────────────

def capacity_bytes(cover_text: str, profile_id: int) -> int:
    """
    Maximum binary payload size (bytes) that can be hidden in cover_text
    using the given profile, accounting for the prefix symbol overhead.

    Computes the largest L with _num_symbols(L, N) <= usable_gaps, i.e.
        L = floor( usable * log(N) / log(256) )

    Two independent estimates are taken and the minimum is returned to avoid
    over-reporting (which could cause embedding to fail after a capacity check).
    """
    clean   = _strip_stego(cover_text)
    n_gaps  = max(0, len(clean) - 1)
    usable  = max(0, n_gaps - _PREFIX_SYMS)
    n_alpha = len(_get_profile_chars(profile_id))
    if n_alpha < 2 or usable == 0:
        return 0
    # Two independent estimates; take minimum so we never over-report
    c1 = int(usable * math.log2(n_alpha) / 8.0)
    c2 = int(usable * math.log(float(n_alpha)) / math.log(256.0))
    return min(c1, c2)


# ── gap index computation ─────────────────────────────────────────────────────

def _gap_indices(n_sym: int, n_gaps: int) -> list:
    """
    Return n_sym evenly-spaced gap indices in [0, n_gaps-1].
    Gap index g means "insert invisible char after clean[g]".
    """
    if n_sym == 0:
        return []
    return [int(i * n_gaps / n_sym) for i in range(n_sym)]


# ── embed ─────────────────────────────────────────────────────────────────────

def _embed_symbols(cover_text: str, all_symbols: str) -> str:
    """
    Spread all_symbols evenly through cover_text at inter-character gaps.
    Cover text is first stripped of any pre-existing stego chars.
    """
    clean  = _strip_stego(cover_text)
    n_sym  = len(all_symbols)
    n_gaps = len(clean) - 1

    if n_sym == 0:
        return clean
    if n_sym > n_gaps:
        raise ValueError(
            f"Cover text too short: {n_gaps} gaps available, "
            f"{n_sym} symbols to embed.  Provide a longer cover text."
        )

    gaps    = _gap_indices(n_sym, n_gaps)
    gap_map = {g: all_symbols[i] for i, g in enumerate(gaps)}

    result: list = []
    for i, ch in enumerate(clean):
        result.append(ch)
        if i in gap_map:
            result.append(gap_map[i])
    return "".join(result)


def embed_payload(cover_text: str, binary_payload: bytes,
                  profile_id: int, password: str) -> str:
    """Full encode pipeline: binary_payload → invisible symbol stream → stego text."""
    alphabet     = _keyed_alphabet(profile_id, password)
    prefix_syms  = _encode_prefix(profile_id, len(binary_payload))
    payload_syms = _encode_base_n(binary_payload, alphabet)
    return _embed_symbols(cover_text, prefix_syms + payload_syms)


# ── extract ───────────────────────────────────────────────────────────────────

def _extract_symbols(stego_text: str) -> str:
    """Return all stego invisible characters from stego_text, in document order."""
    return "".join(ch for ch in stego_text if _is_stego(ch))


def extract_payload(stego_text: str, password: str) -> bytes:
    """
    Full decode pipeline: stego text → binary_payload bytes.

    Bootstrap sequence:
      1. Extract all invisible chars in document order.
      2. Decode first _PREFIX_SYMS using the fixed SAFE alphabet
         → profile_id and total_bytes.
      3. Build key-permuted alphabet for the declared profile.
      4. Compute n_payload_sym = _num_symbols(total_bytes, N).   ← uses §3
      5. Decode next n_payload_sym symbols → total_bytes of payload.
    """
    invisible = _extract_symbols(stego_text)

    if len(invisible) < _PREFIX_SYMS:
        raise ValueError(
            f"Found only {len(invisible)} invisible symbols — "
            f"need at least {_PREFIX_SYMS}.  Is this really a stego file?"
        )

    # Step 1: bootstrap
    profile_id, total_bytes = _decode_prefix(invisible[:_PREFIX_SYMS])

    if profile_id not in _PROFILE_CHARS:
        raise ValueError(
            f"Decoded profile_id={profile_id} is invalid.  "
            "Wrong password or corrupted prefix."
        )

    # Step 2: main payload decode
    alphabet      = _keyed_alphabet(profile_id, password)
    n_payload_sym = _num_symbols(total_bytes, len(alphabet))   # §3 — exact

    payload_window = invisible[_PREFIX_SYMS : _PREFIX_SYMS + n_payload_sym]

    if len(payload_window) < n_payload_sym:
        raise ValueError(
            f"Incomplete payload symbols: expected {n_payload_sym}, "
            f"got {len(payload_window)}.  File may be truncated or corrupted."
        )

    return _decode_base_n(payload_window, alphabet, total_bytes)


# =============================================================================
# §8  TOP-LEVEL WORKFLOWS
# =============================================================================

def encrypt_file_to_stego(
    input_path:  str,
    password:    str,
    cover_text:  str,
    output_path: str,
    profile_id:  int  = PROFILE_SAFE,
    verbose:     bool = True,
) -> bool:
    """
    Encrypt a file and embed it invisibly into cover_text.
    Saves the stego text to output_path (always as .txt).
    Returns True on success.
    """

    def log(msg: str) -> None:
        if verbose: print(f"  [+] {msg}")

    def err(msg: str) -> None:
        print(f"  [!] {msg}", file=sys.stderr)

    # ── 1. Read source file ───────────────────────────────────────────────
    try:
        with open(input_path, "rb") as fh:
            file_data = fh.read()
    except OSError as exc:
        err(f"Cannot read input file: {exc}"); return False

    extension = os.path.splitext(input_path)[1].lstrip(".")
    log(f"Input: {len(file_data):,} bytes  extension='.{extension}'")

    # ── 2. Compress ───────────────────────────────────────────────────────
    compressed, was_compressed = _compress(file_data)
    flags = _FLAG_COMPRESSED if was_compressed else 0
    if was_compressed:
        ratio = len(compressed) / len(file_data) * 100
        log(f"Compressed: {len(compressed):,} bytes ({ratio:.1f}% of original)")
    else:
        log("Compression skipped (not beneficial — already-compressed format?)")

    # ── 3. AES-256-GCM encrypt ────────────────────────────────────────────
    log(f"Encrypting  [PBKDF2 {_KDF_ITER // 1000}k iters + AES-256-GCM] ...")
    salt, nonce, ciphertext, tag = _aes_encrypt(compressed, password)
    log(f"Ciphertext: {len(ciphertext):,} bytes + {_TAG_LEN}-B auth tag")

    # ── 4. Build compact binary payload ───────────────────────────────────
    binary_payload = _build_payload(
        flags, profile_id, extension, salt, nonce, ciphertext, tag
    )
    log(f"Binary payload: {len(binary_payload):,} bytes  (header + ciphertext + tag)")

    # ── 5. Capacity check ─────────────────────────────────────────────────
    cap = capacity_bytes(cover_text, profile_id)
    if len(binary_payload) > cap:
        err(
            f"Insufficient cover capacity!\n"
            f"    Payload  : {len(binary_payload):,} bytes\n"
            f"    Available: {cap:,} bytes  "
            f"[profile {PROFILE_NAMES[profile_id]}]\n"
            f"    → Use a longer cover text or a higher-capacity profile."
        )
        return False

    util = len(binary_payload) / cap * 100 if cap > 0 else 100.0
    log(
        f"Cover capacity ({PROFILE_NAMES[profile_id]}): {cap:,} bytes  "
        f"— utilization {util:.1f}%"
    )

    # ── 6. Embed ──────────────────────────────────────────────────────────
    log("Embedding invisible symbols into cover text ...")
    stego  = embed_payload(cover_text, binary_payload, profile_id, password)
    n_syms = sum(1 for ch in stego if _is_stego(ch))
    log(
        f"Embedded {n_syms:,} invisible symbols "
        f"into {len(stego):,}-char stego text"
    )

    # ── 7. Save ───────────────────────────────────────────────────────────
    out = os.path.splitext(output_path)[0] + ".txt"
    try:
        with open(out, "w", encoding="utf-8") as fh:
            fh.write(stego)
    except OSError as exc:
        err(f"Cannot write output file: {exc}"); return False

    log(f"Saved: {out}")
    return True


def decrypt_stego_file(
    stego_path:  str,
    password:    str,
    output_path: str,
    verbose:     bool = True,
) -> bool:
    """
    Extract and decrypt the hidden file from a stego .txt.
    The output file extension is recovered automatically from the payload header.
    Returns True on success.
    """

    def log(msg: str) -> None:
        if verbose: print(f"  [+] {msg}")

    def err(msg: str) -> None:
        print(f"  [!] {msg}", file=sys.stderr)

    # ── 1. Read stego file ────────────────────────────────────────────────
    try:
        with open(stego_path, "r", encoding="utf-8") as fh:
            stego_text = fh.read()
    except OSError as exc:
        err(f"Cannot read stego file: {exc}"); return False

    n_invisible = sum(1 for ch in stego_text if _is_stego(ch))
    log(f"Read {len(stego_text):,} chars  ({n_invisible:,} invisible symbols)")

    if n_invisible == 0:
        err("No invisible stego symbols found — is this really a stego file?")
        return False

    # ── 2. Extract binary payload (bootstrap-safe) ────────────────────────
    log("Extracting payload symbols and decoding ...")
    try:
        binary_payload = extract_payload(stego_text, password)
    except ValueError as exc:
        err(f"Extraction error: {exc}"); return False

    log(f"Extracted binary payload: {len(binary_payload):,} bytes")

    # ── 3. Parse compact header ───────────────────────────────────────────
    try:
        info = _parse_payload(binary_payload)
    except (ValueError, struct.error) as exc:
        err(f"Header parse failed: {exc}"); return False

    pname = PROFILE_NAMES.get(info["profile_id"], f"#{info['profile_id']}")
    log(
        f"Profile={pname}  "
        f"extension='.{info['extension']}'  "
        f"compressed={bool(info['flags'] & _FLAG_COMPRESSED)}"
    )

    # ── 4. AES-256-GCM decrypt ────────────────────────────────────────────
    log("Decrypting ...")
    try:
        decrypted = _aes_decrypt(
            info["salt"], info["nonce"],
            info["ciphertext"], info["tag"],
            password,
        )
    except ValueError as exc:
        err(f"Decryption failed: {exc}"); return False

    log(f"Decrypted: {len(decrypted):,} bytes")

    # ── 5. Decompress if needed ───────────────────────────────────────────
    if info["flags"] & _FLAG_COMPRESSED:
        log("Decompressing ...")
        decrypted = _decompress(decrypted)
        log(f"Decompressed: {len(decrypted):,} bytes")

    # ── 6. Write output with recovered extension ──────────────────────────
    base  = os.path.splitext(output_path)[0]
    ext   = info["extension"]
    final = f"{base}.{ext}" if ext else base

    try:
        with open(final, "wb") as fh:
            fh.write(decrypted)
    except OSError as exc:
        err(f"Cannot write output file: {exc}"); return False

    log(f"Saved: {final}")
    return True


# =============================================================================
# §9  UTILITIES & SELF-TEST
# =============================================================================

def print_profiles() -> None:
    safe_bps = math.log2(len(_SAFE_CHARS))
    print(f"\n  {'ID':<4} {'Profile':<12} {'Chars':>6} {'Bits/sym':>10} {'vs SAFE':>9}  Status")
    print(f"  {'─'*4} {'─'*12} {'─'*6} {'─'*10} {'─'*9}  {'─'*48}")
    for pid in (PROFILE_SAFE, PROFILE_EXTENDED, PROFILE_MAX):
        info   = profile_info(pid)
        mult   = info["bits_per_sym"] / safe_bps
        status = PROFILE_STATUS[pid]
        print(
            f"  {pid:<4} {info['name']:<12} {info['size']:>6} "
            f"{info['bits_per_sym']:>10.3f} {mult:>8.2f}×  {status}"
        )
    print(f"\n  Length prefix: {_PREFIX_SYMS} symbols (fixed, SAFE alphabet, unkeyed)")
    print(f"  Format version: {_VERSION}")
    print()


def estimate_cover_chars(file_bytes: int, profile_id: int,
                         compression_ratio: float = 0.65) -> int:
    """
    Estimate minimum cover text character count for the given file size.
    compression_ratio: assumed fraction after zlib (0.65 is conservative).
    """
    n_alpha = len(_get_profile_chars(profile_id))
    # header overhead (conservative): ~60 bytes
    payload = int(file_bytes * compression_ratio) + 60
    n_syms  = _num_symbols(payload, n_alpha) + _PREFIX_SYMS   # §3 — exact
    return n_syms + 2   # need n_syms gaps → n_syms+1 chars minimum, +1 safety


# -----------------------------------------------------------------------------
# Stage 0 self-test — Unicode alphabet validation
# -----------------------------------------------------------------------------

def test_unicode_alphabets(verbose: bool = True) -> bool:
    """
    Stage 0: Validate all three Unicode alphabet profiles.

    Checks (per profile and per character):
      1.  Correct character counts (11 / 55 / 392)
      2.  No duplicates within any profile
      3.  Subset relationships: SAFE ⊆ EXTENDED ⊆ MAX
      4.  Correct tier assignments (T1 in SAFE, T1+T2 in EXTENDED, etc.)
      5.  UTF-8 encode/decode identity for every character
      6.  UTF-8 file write/read identity for every character
      7.  Python string-op stability (len, split, replace, strip)
      8.  SAFE characters all in expected Unicode categories (Cf or Mn)
      9.  _ALL_STEGO_CHARS coverage (extraction set == MAX set)
      10. NFKC stability: SAFE must pass (critical); EXTENDED instability
          for U+3164/U+FFA0 is reported as a WARNING, not a hard failure.

    Returns True only if all hard checks pass.
    U+3164 and U+FFA0 NFKC warnings are informational only.
    """
    EXPECTED_COUNTS = {
        PROFILE_SAFE:     11,
        PROFILE_EXTENDED: 55,
        PROFILE_MAX:      392,
    }

    # Characters known to fail NFKC/NFKD (score 11/13) — kept deliberately in
    # Tier 2/EXTENDED but must not be used in NFKC-normalising environments.
    NFKC_UNSTABLE = {"\u3164", "\uFFA0"}  # U+3164 and U+FFA0 → U+1160

    print("\n  ── STAGE 0: UNICODE ALPHABET VALIDATION ─────────────────────────────────")
    print(f"  Profiles : SAFE ({EXPECTED_COUNTS[PROFILE_SAFE]}) · "
          f"EXTENDED ({EXPECTED_COUNTS[PROFILE_EXTENDED]}) · "
          f"MAX ({EXPECTED_COUNTS[PROFILE_MAX]})")
    print(f"  Checks   : counts · uniqueness · subset · tiers · UTF-8 "
          f"· file I/O · string-ops · categories")
    print()

    all_ok   = True
    failures: list = []

    def fail(msg: str) -> None:
        nonlocal all_ok
        all_ok = False
        failures.append(msg)

    # ── Check 1: counts ────────────────────────────────────────────────────
    for pid, expected in EXPECTED_COUNTS.items():
        actual = len(_PROFILE_CHARS[pid])
        if actual != expected:
            fail(f"Count mismatch {PROFILE_NAMES[pid]}: "
                 f"expected {expected}, got {actual}")
    print(f"  [{'✓' if all_ok else '✗'}] Counts: "
          f"SAFE={len(_SAFE_CHARS)}  EXTENDED={len(_EXTENDED_CHARS)}  MAX={len(_MAX_CHARS)}")

    # ── Check 2: uniqueness ────────────────────────────────────────────────
    ok2 = True
    for pid in (PROFILE_SAFE, PROFILE_EXTENDED, PROFILE_MAX):
        lst = _PROFILE_CHARS[pid]
        dupes = len(lst) - len(set(lst))
        if dupes:
            fail(f"Duplicates in {PROFILE_NAMES[pid]}: {dupes} duplicate(s)")
            ok2 = False
    print(f"  [{'✓' if ok2 else '✗'}] No duplicates in any profile")

    # ── Check 3: subset relationships ──────────────────────────────────────
    safe_set = frozenset(_SAFE_CHARS)
    ext_set  = frozenset(_EXTENDED_CHARS)
    max_set  = frozenset(_MAX_CHARS)
    ok3 = safe_set <= ext_set and ext_set <= max_set
    if not (safe_set <= ext_set):
        fail(f"SAFE not a subset of EXTENDED: "
             f"extra {[hex(ord(c)) for c in safe_set - ext_set]}")
    if not (ext_set <= max_set):
        fail(f"EXTENDED not a subset of MAX: "
             f"extra {[hex(ord(c)) for c in ext_set - max_set]}")
    print(f"  [{'✓' if ok3 else '✗'}] SAFE ⊆ EXTENDED ⊆ MAX")

    # ── Check 4: tier assignments ──────────────────────────────────────────
    ok4 = True
    # All SAFE chars must be T1
    for ch in _SAFE_CHARS:
        if _CHAR_TIERS.get(ch) != TIER_RELIABLE:
            fail(f"Non-T1 char in SAFE: U+{ord(ch):04X}")
            ok4 = False
    # EXTENDED-only chars must be T2
    for ch in _EXTENDED_CHARS:
        if ch not in safe_set:
            t = _CHAR_TIERS.get(ch)
            if t != TIER_GOOD:
                fail(f"Unexpected tier {t} for EXTENDED-only char U+{ord(ch):04X}")
                ok4 = False
    # MAX-only chars must be T3
    for ch in _MAX_CHARS:
        if ch not in ext_set:
            t = _CHAR_TIERS.get(ch)
            if t != TIER_EXPERIMENTAL:
                fail(f"Unexpected tier {t} for MAX-only char U+{ord(ch):04X}")
                ok4 = False
    t1 = sum(1 for t in _CHAR_TIERS.values() if t == TIER_RELIABLE)
    t2 = sum(1 for t in _CHAR_TIERS.values() if t == TIER_GOOD)
    t3 = sum(1 for t in _CHAR_TIERS.values() if t == TIER_EXPERIMENTAL)
    print(f"  [{'✓' if ok4 else '✗'}] Tier assignments correct: "
          f"T1={t1}  T2={t2}  T3={t3}")

    # ── Check 5: UTF-8 encode/decode identity ─────────────────────────────
    ok5 = True
    for ch in _MAX_CHARS:
        try:
            if ch.encode("utf-8").decode("utf-8") != ch:
                fail(f"UTF-8 round-trip failed for U+{ord(ch):04X}")
                ok5 = False
        except Exception as exc:
            fail(f"UTF-8 encode error for U+{ord(ch):04X}: {exc}")
            ok5 = False
    print(f"  [{'✓' if ok5 else '✗'}] UTF-8 encode/decode identity ({len(_MAX_CHARS)} chars)")

    # ── Check 6: file write/read round-trip (UTF-8) ────────────────────────
    ok6 = True
    try:
        sample = "".join(_MAX_CHARS)
        with tempfile.NamedTemporaryFile(
                mode="w", suffix=".txt", encoding="utf-8",
                delete=False) as tf:
            tf.write(sample)
            fpath = tf.name
        with open(fpath, "r", encoding="utf-8") as fh:
            recovered = fh.read()
        os.remove(fpath)
        if recovered != sample:
            # Find which char(s) changed
            lost = [ch for ch in _MAX_CHARS if ch not in recovered]
            fail(f"File UTF-8 round-trip lost {len(lost)} chars: "
                 f"{[hex(ord(c)) for c in lost[:5]]}")
            ok6 = False
    except Exception as exc:
        fail(f"File write/read test error: {exc}")
        ok6 = False
    print(f"  [{'✓' if ok6 else '✗'}] UTF-8 file write/read identity "
          f"({'all ' + str(len(_MAX_CHARS)) + ' chars survived' if ok6 else 'FAILED'})")

    # ── Check 7: Python string-op stability ────────────────────────────────
    ok7 = True
    for ch in _MAX_CHARS:
        try:
            s = f"A{ch}B"
            if len(s) != 3:
                fail(f"len() wrong for U+{ord(ch):04X}: {len(s)} != 3")
                ok7 = False
                continue
            if s.replace(ch, "") != "AB":
                fail(f"replace() failed for U+{ord(ch):04X}")
                ok7 = False
            if s.split(ch) != ["A", "B"]:
                fail(f"split() failed for U+{ord(ch):04X}")
                ok7 = False
        except Exception as exc:
            fail(f"String-op error U+{ord(ch):04X}: {exc}")
            ok7 = False
    print(f"  [{'✓' if ok7 else '✗'}] Python string ops (len/replace/split) stable")

    # ── Check 8: SAFE chars are Cf or Mn (correct Unicode categories) ──────
    ok8 = True
    allowed_cats = {"Cf", "Mn"}
    for ch in _SAFE_CHARS:
        cat = unicodedata.category(ch)
        if cat not in allowed_cats:
            fail(f"Unexpected category {cat!r} for SAFE char U+{ord(ch):04X}")
            ok8 = False
    print(f"  [{'✓' if ok8 else '✗'}] SAFE chars all in expected Unicode categories "
          f"(Cf/Mn)")

    # ── Check 9: _ALL_STEGO_CHARS equals MAX set ───────────────────────────
    ok9 = (_ALL_STEGO_CHARS == max_set)
    if not ok9:
        extra   = _ALL_STEGO_CHARS - max_set
        missing = max_set - _ALL_STEGO_CHARS
        if extra:   fail(f"_ALL_STEGO_CHARS has {len(extra)} extra chars")
        if missing: fail(f"_ALL_STEGO_CHARS missing {len(missing)} chars")
    print(f"  [{'✓' if ok9 else '✗'}] _ALL_STEGO_CHARS == MAX set "
          f"({len(_ALL_STEGO_CHARS)} chars)")

    # ── Check 10: NFKC stability — SAFE must be stable; warn for EXTENDED ──
    ok10_safe = True
    for ch in _SAFE_CHARS:
        normed = unicodedata.normalize("NFKC", ch)
        if normed != ch:
            fail(f"SAFE char U+{ord(ch):04X} changes under NFKC → "
                 f"U+{ord(normed):04X}")
            ok10_safe = False
    print(f"  [{'✓' if ok10_safe else '✗'}] SAFE chars all NFKC-stable "
          f"(critical: prefix uses SAFE alphabet)")

    # Informational: which EXTENDED chars are NFKC-unstable (does NOT fail Stage 0)
    nfkc_unstable_ext = []
    for ch in _EXTENDED_CHARS:
        normed = unicodedata.normalize("NFKC", ch)
        if normed != ch:
            nfkc_unstable_ext.append((ch, normed))
    if nfkc_unstable_ext:
        print(f"  [⚠] EXTENDED has {len(nfkc_unstable_ext)} NFKC-unstable "
              f"char(s) — known, deliberate, documented:")
        for ch, normed in nfkc_unstable_ext:
            print(f"      U+{ord(ch):04X} → U+{ord(normed[0]):04X}  "
                  f"(avoid EXTENDED in NFKC-normalising environments)")
    else:
        print(f"  [✓] No NFKC-unstable chars in EXTENDED")

    # ── Summary ────────────────────────────────────────────────────────────
    print()
    if all_ok:
        print("  Stage 0 PASSED ✓  (10/10 check groups, 0 failures)")
    else:
        print(f"  Stage 0 FAILED ✗  ({len(failures)} failure(s)):")
        for msg in failures:
            print(f"    • {msg}")
    print()
    return all_ok


# -----------------------------------------------------------------------------
# Stage 1 self-test — pure base-N arithmetic, no Unicode
# -----------------------------------------------------------------------------

def test_base_n(verbose: bool = True) -> bool:
    """
    Stage 1 self-test: verify _encode_bytes_to_digits / _decode_digits_to_bytes
    for a range of alphabet sizes N, without any Unicode involvement.

    Tested N values : 2, 4, 8, 10, 16, 26, 64, 122, 128, 256, 300
    Test patterns   : empty · 1-byte (0x00, 0xFF, 0xA7) · 2-byte 0x00FF
                      · 10-byte all-zero · 10-byte all-0xFF · 10-byte random
                      · 100-byte random · leading-zero 10-byte
                      · 1 000-byte random · 100-byte all-zero · 100-byte all-0xFF

    Returns True only if every test case passes for every N.
    """
    STAGE1_N_VALUES = [2, 4, 8, 10, 16, 26, 64, 122, 128, 256, 300]

    # Build test cases once per test_base_n() call so random data varies
    test_cases = [
        ("empty",              b""),
        ("1-B 0x00",           b"\x00"),
        ("1-B 0xFF",           b"\xFF"),
        ("1-B 0xA7",           b"\xA7"),
        ("2-B 0x00FF",         b"\x00\xFF"),
        ("10-B all-zero",      b"\x00" * 10),
        ("10-B all-0xFF",      b"\xFF" * 10),
        ("10-B random",        os.urandom(10)),
        ("100-B random",       os.urandom(100)),
        ("leading zeros 10-B", b"\x00\x00\x00" + os.urandom(7)),
        ("1000-B random",      os.urandom(1000)),
        ("100-B all-zero",     b"\x00" * 100),
        ("100-B all-0xFF",     b"\xFF" * 100),
    ]

    n_cases = len(test_cases)

    print("\n  ── STAGE 1: BASE-N ENCODE/DECODE SELF-TEST ──────────────────────────────")
    print(f"  N values  : {STAGE1_N_VALUES}")
    print(f"  Cases/N   : {n_cases}  "
          "(empty · 1-B · 2-B · all-zero · all-0xFF · random · leading-zero · 1 kB)")
    print()
    print(f"  {'N':>5}  {'log₂N':>7}  {'100B→k':>7}  result")
    print(f"  {'─'*5}  {'─'*7}  {'─'*7}  {'─'*42}")

    all_ok   = True
    failures: list = []

    for n in STAGE1_N_VALUES:
        log2n      = math.log2(n)
        k_100      = _num_symbols(100, n)
        n_fail_before = len(failures)

        for label, data in test_cases:
            try:
                # ── encode ────────────────────────────────────────────────
                digits = _encode_bytes_to_digits(data, n)

                # Structural invariants
                expected_k = _num_symbols(len(data), n)
                if len(digits) != expected_k:
                    raise AssertionError(
                        f"digit count {len(digits)} != _num_symbols={expected_k}"
                    )
                if digits and (min(digits) < 0 or max(digits) >= n):
                    raise AssertionError(
                        f"digit(s) outside [0,{n}): "
                        f"min={min(digits)}, max={max(digits)}"
                    )

                # ── decode ────────────────────────────────────────────────
                recovered = _decode_digits_to_bytes(digits, n, len(data))

                if recovered != data:
                    raise AssertionError(
                        "round-trip mismatch\n"
                        f"  original : {data.hex()}\n"
                        f"  recovered: {recovered.hex()}"
                    )

            except Exception as exc:
                all_ok = False
                failures.append((n, label, str(exc)))

        n_failed = len(failures) - n_fail_before
        n_passed = n_cases - n_failed

        if n_failed == 0:
            print(f"  {n:>5}  {log2n:>7.4f}  {k_100:>7}  ✓ {n_passed}/{n_cases}")
        else:
            print(f"  {n:>5}  {log2n:>7.4f}  {k_100:>7}  ✗ {n_passed}/{n_cases}"
                  f"  ({n_failed} FAILED)")

    total = len(STAGE1_N_VALUES) * n_cases
    print()
    if all_ok:
        print(f"  Stage 1 PASSED ✓  ({total}/{total} cases, 0 failures)")
    else:
        print(f"  Stage 1 FAILED ✗  ({len(failures)}/{total} cases failed):")
        for fn, label, msg in failures:
            short = msg.splitlines()[0][:70]
            print(f"    N={fn:<4}  {label:<24}  {short}")
    print()
    return all_ok


# -----------------------------------------------------------------------------
# Stage 2 + combined self_test
# -----------------------------------------------------------------------------

def self_test(verbose: bool = True) -> bool:
    """
    Full self-test:
      Stage 0 — Unicode alphabet validation (counts, uniqueness, tiers, UTF-8,
                file I/O, string ops, categories, _ALL_STEGO_CHARS coverage)
      Stage 1 — Base-N arithmetic (11 N values × 13 patterns = 143 cases)
      Stage 2 — Full encrypt → embed → extract → decrypt round-trip
                for all three alphabet profiles (SAFE / EXTENDED / MAX)

    Returns True only if all tests pass.
    Later stages are skipped when earlier stages fail.
    """

    # ── Stage 0: Unicode alphabet validation ─────────────────────────────────
    stage0_ok = test_unicode_alphabets(verbose=verbose)
    if not stage0_ok:
        print("  !! Stage 0 failures detected — skipping Stage 1 and Stage 2.")
        return False

    # ── Stage 1: pure base-N arithmetic ──────────────────────────────────────
    stage1_ok = test_base_n(verbose=verbose)
    if not stage1_ok:
        print("  !! Stage 1 failures detected — skipping Stage 2.")
        return False

    # ── Stage 2: full encrypt → embed → extract → decrypt ────────────────────
    print("\n  ── STAGE 2: FULL ROUND-TRIP SELF-TEST ──────────────────────────────────")

    password  = "TestP@ssw0rd!"
    test_data = b"The quick brown fox jumps over the lazy dog. " * 20 + os.urandom(80)

    cover = (
        "In the beginning God created the heaven and the earth.  "
        "And the earth was without form, and void; and darkness was upon "
        "the face of the deep.  And the Spirit of God moved upon the face "
        "of the waters.  And God said, Let there be light: and there was light."
    ) * 40   # ~7 500 chars

    all_ok = True

    for profile_id in (PROFILE_SAFE, PROFILE_EXTENDED, PROFILE_MAX):
        pname = PROFILE_NAMES[profile_id]
        print(f"\n  Profile: {pname}")

        with tempfile.NamedTemporaryFile(suffix=".bin", delete=False) as tf:
            tf.write(test_data)
            in_path = tf.name

        stego_path = in_path + "_stego.txt"
        out_base   = in_path + "_recovered"

        try:
            ok = encrypt_file_to_stego(
                in_path, password, cover, stego_path,
                profile_id, verbose=verbose,
            )
            if not ok:
                print("    [✗] Encryption failed"); all_ok = False; continue

            ok = decrypt_stego_file(
                stego_path, password, out_base, verbose=verbose,
            )
            if not ok:
                print("    [✗] Decryption failed"); all_ok = False; continue

            recovered_path = out_base + ".bin"
            with open(recovered_path, "rb") as fh:
                recovered = fh.read()

            if recovered == test_data:
                print(f"    [✓] Round-trip OK — {len(test_data):,} bytes verified")
            else:
                print("    [✗] Data mismatch!")
                all_ok = False

        finally:
            for p in [in_path, stego_path, out_base + ".bin"]:
                try:
                    os.remove(p)
                except OSError:
                    pass

    print(f"\n  {'All tests passed ✓' if all_ok else 'Some tests FAILED ✗'}")
    return all_ok


# =============================================================================
# §10  CLI — Interactive menu + argparse
# =============================================================================

_BANNER = r"""
  ╔══════════════════════════════════════════════════════════════╗
  ║      U N I C O D E   S T E G A N O G R A P H Y   V 2       ║
  ║   AES-256-GCM · PBKDF2-SHA256 · Base-N · Adaptive Profiles  ║
  ╚══════════════════════════════════════════════════════════════╝"""


def _read_cover_interactive() -> str:
    print("\n  Cover text source:")
    print("    [1] Load from file")
    print("    [2] Type / paste  (end with a line containing only '---')")
    src = input("  Choice [1/2]: ").strip()

    if src == "1":
        path = input("  Cover text file: ").strip()
        try:
            with open(path, "r", encoding="utf-8") as fh:
                return fh.read()
        except OSError as exc:
            sys.exit(f"  [!] Cannot open cover file: {exc}")

    print("  Enter / paste cover text (finish with '---' on its own line):")
    lines: list = []
    while True:
        ln = input()
        if ln.strip() == "---":
            break
        lines.append(ln)
    return "\n".join(lines)


def _menu_encrypt() -> None:
    print("\n  ── ENCRYPT ──────────────────────────────────────────────────")
    password = input("  Password: ").strip()
    if not password:
        print("  [!] Password cannot be empty."); return

    in_path = input("  Input file to hide: ").strip()
    if not os.path.isfile(in_path):
        print(f"  [!] File not found: {in_path}"); return

    cover = _read_cover_interactive()

    print_profiles()
    p = input("  Profile [0=SAFE / 1=EXTENDED / 2=MAX, default 0]: ").strip()
    profile_id = int(p) if p in ("0", "1", "2") else PROFILE_SAFE

    file_sz = os.path.getsize(in_path)
    cap     = capacity_bytes(cover, profile_id)
    print(
        f"\n  Estimated payload after compress+encrypt: "
        f"~{int(file_sz * 0.65) + 60:,} bytes"
    )
    print(f"  Cover capacity [{PROFILE_NAMES[profile_id]}]: {cap:,} bytes")
    if int(file_sz * 0.65) + 60 > cap:
        print(
            "  [!] Cover text may be too short.  "
            "Consider a longer text or a higher profile."
        )

    out_path = input("  Output path (saved as .txt): ").strip()
    print()
    ok = encrypt_file_to_stego(in_path, password, cover, out_path, profile_id)
    print(f"\n  {'✓ Encryption complete!' if ok else '✗ Encryption failed.'}")


def _menu_decrypt() -> None:
    print("\n  ── DECRYPT ──────────────────────────────────────────────────")
    password   = input("  Password: ").strip()
    stego_path = input("  Stego .txt file: ").strip()
    if not os.path.isfile(stego_path):
        print(f"  [!] File not found: {stego_path}"); return
    out_path = input("  Output path (extension auto-detected): ").strip()
    print()
    ok = decrypt_stego_file(stego_path, password, out_path)
    print(f"\n  {'✓ Decryption complete!' if ok else '✗ Decryption failed.'}")


def _menu_info() -> None:
    print_profiles()
    s = input(
        "  Enter a file size in bytes to estimate required cover text "
        "(or Enter to skip): "
    ).strip()
    if s.isdigit():
        file_bytes = int(s)
        print(f"\n  Minimum cover text characters for a {file_bytes:,}-byte file:")
        for pid in (PROFILE_SAFE, PROFILE_EXTENDED, PROFILE_MAX):
            n = estimate_cover_chars(file_bytes, pid)
            print(f"    {PROFILE_NAMES[pid]:12s}: >= {n:,} characters")
    print()


def _interactive_menu() -> None:
    print(_BANNER)
    print()
    print("  [1]  Encrypt file  →  stego text")
    print("  [2]  Decrypt stego text  →  original file")
    print("  [3]  Profile & capacity info")
    print("  [4]  Full self-test  (Stage 0 Unicode + Stage 1 base-N + Stage 2 round-trip)")
    print("  [5]  Stage 0 only: Unicode alphabet validation")
    print("  [6]  Stage 1 only: base-N arithmetic test")
    print("  [Q]  Quit")
    choice = input("\n  Choice: ").strip().upper()

    dispatch = {
        "1": _menu_encrypt,
        "2": _menu_decrypt,
        "3": _menu_info,
        "4": lambda: self_test(verbose=True),
        "5": lambda: test_unicode_alphabets(verbose=True),
        "6": lambda: test_base_n(verbose=True),
    }
    if choice in dispatch:
        dispatch[choice]()
    elif choice == "Q":
        sys.exit(0)
    else:
        print("  Invalid choice.")


def _build_argparser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="stego_v2",
        description="Unicode Steganography V2 — hide files inside plain text",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  python stego_v2.py encrypt secret.pdf cover.txt output --password mykey\n"
            "  python stego_v2.py decrypt output.txt recovered --password mykey\n"
            "  python stego_v2.py info --profile 2 --filesize 50000\n"
            "  python stego_v2.py test\n"
            "  python stego_v2.py test-unicode\n"
            "  python stego_v2.py test-base-n\n"
        ),
    )
    sub = parser.add_subparsers(dest="cmd")

    # ── encrypt ──
    enc = sub.add_parser("encrypt", help="Encrypt a file into a stego text")
    enc.add_argument("input",  help="File to hide")
    enc.add_argument("cover",  help="Cover text file (.txt)")
    enc.add_argument("output", help="Output path (saved as .txt)")
    enc.add_argument("-p", "--password", required=True, help="Encryption password")
    enc.add_argument(
        "--profile", type=int, choices=[0, 1, 2], default=PROFILE_SAFE,
        metavar="N",
        help="Alphabet profile: 0=SAFE (11), 1=EXTENDED (55), 2=MAX (409, experimental).  Default 0.",
    )
    enc.add_argument("-q", "--quiet", action="store_true", help="Suppress progress output")

    # ── decrypt ──
    dec = sub.add_parser("decrypt", help="Decrypt a stego text to recover the original file")
    dec.add_argument("stego",  help="Stego .txt file")
    dec.add_argument("output", help="Output path (extension auto-detected from payload)")
    dec.add_argument("-p", "--password", required=True, help="Decryption password")
    dec.add_argument("-q", "--quiet", action="store_true", help="Suppress progress output")

    # ── info ──
    inf = sub.add_parser("info", help="Show alphabet profile details")
    inf.add_argument(
        "--profile", type=int, choices=[0, 1, 2], default=None,
        metavar="N", help="Specific profile to query (default: all)",
    )
    inf.add_argument(
        "--filesize", type=int, default=None,
        metavar="BYTES", help="Estimate required cover size for this file size",
    )

    # ── test / test-unicode / test-base-n ──
    sub.add_parser("test",
                   help="Run full self-test (Stage 0 Unicode + Stage 1 base-N + Stage 2 round-trip)")
    sub.add_parser("test-unicode",
                   help="Run Stage 0 Unicode alphabet validation only")
    sub.add_parser("test-base-n",
                   help="Run Stage 1 base-N arithmetic tests only (no Unicode, no crypto)")

    return parser


def main() -> None:
    if len(sys.argv) > 1:
        parser = _build_argparser()
        args   = parser.parse_args()

        if args.cmd == "encrypt":
            try:
                with open(args.cover, "r", encoding="utf-8") as fh:
                    cover = fh.read()
            except OSError as exc:
                sys.exit(f"[!] Cannot read cover file: {exc}")
            ok = encrypt_file_to_stego(
                args.input, args.password, cover, args.output,
                args.profile, verbose=not args.quiet,
            )
            sys.exit(0 if ok else 1)

        elif args.cmd == "decrypt":
            ok = decrypt_stego_file(
                args.stego, args.password, args.output,
                verbose=not args.quiet,
            )
            sys.exit(0 if ok else 1)

        elif args.cmd == "info":
            print(_BANNER)
            pids = [args.profile] if args.profile is not None \
                   else [PROFILE_SAFE, PROFILE_EXTENDED, PROFILE_MAX]
            print_profiles()
            if args.filesize:
                print(f"  Minimum cover text chars for {args.filesize:,}-byte file:")
                for pid in pids:
                    n = estimate_cover_chars(args.filesize, pid)
                    print(f"    {PROFILE_NAMES[pid]:12s}: >= {n:,} chars")
                print()

        elif args.cmd == "test":
            ok = self_test(verbose=True)
            sys.exit(0 if ok else 1)

        elif args.cmd == "test-unicode":
            ok = test_unicode_alphabets(verbose=True)
            sys.exit(0 if ok else 1)

        elif args.cmd == "test-base-n":
            ok = test_base_n(verbose=True)
            sys.exit(0 if ok else 1)

        else:
            _build_argparser().print_help()

    else:
        _interactive_menu()


if __name__ == "__main__":
    main()
