"""
validated_alphabets.py — Auto-generated by unicode_compat.py
======================================================================
Paste _VALIDATED_*_CHARS into stego_v2.py to replace the hardcoded
_SAFE_CHARS, _EXTENDED_CHARS, and _MAX_CHARS lists.

These alphabets are derived from automated Python tests plus Unicode
semantic classification.  Manual cross-platform testing (browsers,
editors, OS text fields, clipboard) is recommended before production use.
See manual_tests.txt for test strings.
"""

# Total candidates tested: 392
# Tier 1 (RELIABLE): 11 chars
# Tier 2 (GOOD): 44 chars
# Tier 3 (EXPERIMENTAL): 337 chars
# Tier 4 (REJECTED): 0 chars

# ──────────────────────────────────────────────────────────────────
# Profile: SAFE
#   11 chars  ·  3.459 bits/sym
#   vs stego_v2.py default: 10 chars / 3.32 bits/sym
#   capacity improvement: 1.04×
#   Tier threshold: ≤ 1 (RELIABLE)
_VALIDATED_SAFE_CHARS: list = [
    "\u00AD",  # U+00AD SOFT HYPHEN                                T1
    "\u034F",  # U+034F COMBINING GRAPHEME JOINER                  T1
    "\u200B",  # U+200B ZERO WIDTH SPACE                           T1
    "\u200C",  # U+200C ZERO WIDTH NON-JOINER                      T1
    "\u200D",  # U+200D ZERO WIDTH JOINER                          T1
    "\u2060",  # U+2060 WORD JOINER                                T1
    "\u2061",  # U+2061 FUNCTION APPLICATION                       T1
    "\u2062",  # U+2062 INVISIBLE TIMES                            T1
    "\u2063",  # U+2063 INVISIBLE SEPARATOR                        T1
    "\u2064",  # U+2064 INVISIBLE PLUS                             T1
    "\uFEFF",  # U+FEFF ZERO WIDTH NO-BREAK SPACE                  T1
]

# ──────────────────────────────────────────────────────────────────
# Profile: EXTENDED
#   55 chars  ·  5.781 bits/sym
#   vs stego_v2.py default: 26 chars / 4.70 bits/sym
#   capacity improvement: 1.23×
#   Tier threshold: ≤ 2 (GOOD)
_VALIDATED_EXTENDED_CHARS: list = [
    "\u00AD",  # U+00AD SOFT HYPHEN                                T1
    "\u034F",  # U+034F COMBINING GRAPHEME JOINER                  T1
    "\u115F",  # U+115F HANGUL CHOSEONG FILLER                     T2
    "\u1160",  # U+1160 HANGUL JUNGSEONG FILLER                    T2
    "\u17B4",  # U+17B4 KHMER VOWEL INHERENT AQ                    T2
    "\u17B5",  # U+17B5 KHMER VOWEL INHERENT AA                    T2
    "\u180B",  # U+180B MONGOLIAN FREE VARIATION SELECTOR ONE      T2
    "\u180C",  # U+180C MONGOLIAN FREE VARIATION SELECTOR TWO      T2
    "\u180D",  # U+180D MONGOLIAN FREE VARIATION SELECTOR THREE    T2
    "\u180E",  # U+180E MONGOLIAN VOWEL SEPARATOR                  T2
    "\u200B",  # U+200B ZERO WIDTH SPACE                           T1
    "\u200C",  # U+200C ZERO WIDTH NON-JOINER                      T1
    "\u200D",  # U+200D ZERO WIDTH JOINER                          T1
    "\u200E",  # U+200E LEFT-TO-RIGHT MARK                         T2
    "\u200F",  # U+200F RIGHT-TO-LEFT MARK                         T2
    "\u061C",  # U+061C ARABIC LETTER MARK                         T2
    "\u202A",  # U+202A LEFT-TO-RIGHT EMBEDDING                    T2
    "\u202B",  # U+202B RIGHT-TO-LEFT EMBEDDING                    T2
    "\u202C",  # U+202C POP DIRECTIONAL FORMATTING                 T2
    "\u202D",  # U+202D LEFT-TO-RIGHT OVERRIDE                     T2
    "\u202E",  # U+202E RIGHT-TO-LEFT OVERRIDE                     T2
    "\u2066",  # U+2066 LEFT-TO-RIGHT ISOLATE                      T2
    "\u2067",  # U+2067 RIGHT-TO-LEFT ISOLATE                      T2
    "\u2068",  # U+2068 FIRST STRONG ISOLATE                       T2
    "\u2069",  # U+2069 POP DIRECTIONAL ISOLATE                    T2
    "\u2060",  # U+2060 WORD JOINER                                T1
    "\u2061",  # U+2061 FUNCTION APPLICATION                       T1
    "\u2062",  # U+2062 INVISIBLE TIMES                            T1
    "\u2063",  # U+2063 INVISIBLE SEPARATOR                        T1
    "\u2064",  # U+2064 INVISIBLE PLUS                             T1
    "\u206A",  # U+206A INHIBIT SYMMETRIC SWAPPING                 T2
    "\u206B",  # U+206B ACTIVATE SYMMETRIC SWAPPING                T2
    "\u206C",  # U+206C INHIBIT ARABIC FORM SHAPING                T2
    "\u206D",  # U+206D ACTIVATE ARABIC FORM SHAPING               T2
    "\u206E",  # U+206E NATIONAL DIGIT SHAPES                      T2
    "\u206F",  # U+206F NOMINAL DIGIT SHAPES                       T2
    "\u3164",  # U+3164 HANGUL FILLER                              T2
    "\uFFA0",  # U+FFA0 HALFWIDTH HANGUL FILLER                    T2
    "\uFEFF",  # U+FEFF ZERO WIDTH NO-BREAK SPACE                  T1
    "\uFE00",  # U+FE00 VARIATION SELECTOR-1                       T2
    "\uFE01",  # U+FE01 VARIATION SELECTOR-2                       T2
    "\uFE02",  # U+FE02 VARIATION SELECTOR-3                       T2
    "\uFE03",  # U+FE03 VARIATION SELECTOR-4                       T2
    "\uFE04",  # U+FE04 VARIATION SELECTOR-5                       T2
    "\uFE05",  # U+FE05 VARIATION SELECTOR-6                       T2
    "\uFE06",  # U+FE06 VARIATION SELECTOR-7                       T2
    "\uFE07",  # U+FE07 VARIATION SELECTOR-8                       T2
    "\uFE08",  # U+FE08 VARIATION SELECTOR-9                       T2
    "\uFE09",  # U+FE09 VARIATION SELECTOR-10                      T2
    "\uFE0A",  # U+FE0A VARIATION SELECTOR-11                      T2
    "\uFE0B",  # U+FE0B VARIATION SELECTOR-12                      T2
    "\uFE0C",  # U+FE0C VARIATION SELECTOR-13                      T2
    "\uFE0D",  # U+FE0D VARIATION SELECTOR-14                      T2
    "\uFE0E",  # U+FE0E VARIATION SELECTOR-15                      T2
    "\uFE0F",  # U+FE0F VARIATION SELECTOR-16                      T2
]

# ──────────────────────────────────────────────────────────────────
# Profile: MAX
#   392 chars  ·  8.615 bits/sym
#   vs stego_v2.py default: 122 chars / 6.93 bits/sym
#   capacity improvement: 1.24×
#   Tier threshold: ≤ 3 (EXPERIMENTAL)
_VALIDATED_MAX_CHARS: list = [
    "\u00AD",  # U+00AD SOFT HYPHEN                                T1
    "\u034F",  # U+034F COMBINING GRAPHEME JOINER                  T1
    "\u115F",  # U+115F HANGUL CHOSEONG FILLER                     T2
    "\u1160",  # U+1160 HANGUL JUNGSEONG FILLER                    T2
    "\u17B4",  # U+17B4 KHMER VOWEL INHERENT AQ                    T2
    "\u17B5",  # U+17B5 KHMER VOWEL INHERENT AA                    T2
    "\u180B",  # U+180B MONGOLIAN FREE VARIATION SELECTOR ONE      T2
    "\u180C",  # U+180C MONGOLIAN FREE VARIATION SELECTOR TWO      T2
    "\u180D",  # U+180D MONGOLIAN FREE VARIATION SELECTOR THREE    T2
    "\u180E",  # U+180E MONGOLIAN VOWEL SEPARATOR                  T2
    "\u200B",  # U+200B ZERO WIDTH SPACE                           T1
    "\u200C",  # U+200C ZERO WIDTH NON-JOINER                      T1
    "\u200D",  # U+200D ZERO WIDTH JOINER                          T1
    "\u200E",  # U+200E LEFT-TO-RIGHT MARK                         T2
    "\u200F",  # U+200F RIGHT-TO-LEFT MARK                         T2
    "\u061C",  # U+061C ARABIC LETTER MARK                         T2
    "\u202A",  # U+202A LEFT-TO-RIGHT EMBEDDING                    T2
    "\u202B",  # U+202B RIGHT-TO-LEFT EMBEDDING                    T2
    "\u202C",  # U+202C POP DIRECTIONAL FORMATTING                 T2
    "\u202D",  # U+202D LEFT-TO-RIGHT OVERRIDE                     T2
    "\u202E",  # U+202E RIGHT-TO-LEFT OVERRIDE                     T2
    "\u2066",  # U+2066 LEFT-TO-RIGHT ISOLATE                      T2
    "\u2067",  # U+2067 RIGHT-TO-LEFT ISOLATE                      T2
    "\u2068",  # U+2068 FIRST STRONG ISOLATE                       T2
    "\u2069",  # U+2069 POP DIRECTIONAL ISOLATE                    T2
    "\u2060",  # U+2060 WORD JOINER                                T1
    "\u2061",  # U+2061 FUNCTION APPLICATION                       T1
    "\u2062",  # U+2062 INVISIBLE TIMES                            T1
    "\u2063",  # U+2063 INVISIBLE SEPARATOR                        T1
    "\u2064",  # U+2064 INVISIBLE PLUS                             T1
    "\u206A",  # U+206A INHIBIT SYMMETRIC SWAPPING                 T2
    "\u206B",  # U+206B ACTIVATE SYMMETRIC SWAPPING                T2
    "\u206C",  # U+206C INHIBIT ARABIC FORM SHAPING                T2
    "\u206D",  # U+206D ACTIVATE ARABIC FORM SHAPING               T2
    "\u206E",  # U+206E NATIONAL DIGIT SHAPES                      T2
    "\u206F",  # U+206F NOMINAL DIGIT SHAPES                       T2
    "\u3164",  # U+3164 HANGUL FILLER                              T2
    "\uFFA0",  # U+FFA0 HALFWIDTH HANGUL FILLER                    T2
    "\uFEFF",  # U+FEFF ZERO WIDTH NO-BREAK SPACE                  T1
    "\uFE00",  # U+FE00 VARIATION SELECTOR-1                       T2
    "\uFE01",  # U+FE01 VARIATION SELECTOR-2                       T2
    "\uFE02",  # U+FE02 VARIATION SELECTOR-3                       T2
    "\uFE03",  # U+FE03 VARIATION SELECTOR-4                       T2
    "\uFE04",  # U+FE04 VARIATION SELECTOR-5                       T2
    "\uFE05",  # U+FE05 VARIATION SELECTOR-6                       T2
    "\uFE06",  # U+FE06 VARIATION SELECTOR-7                       T2
    "\uFE07",  # U+FE07 VARIATION SELECTOR-8                       T2
    "\uFE08",  # U+FE08 VARIATION SELECTOR-9                       T2
    "\uFE09",  # U+FE09 VARIATION SELECTOR-10                      T2
    "\uFE0A",  # U+FE0A VARIATION SELECTOR-11                      T2
    "\uFE0B",  # U+FE0B VARIATION SELECTOR-12                      T2
    "\uFE0C",  # U+FE0C VARIATION SELECTOR-13                      T2
    "\uFE0D",  # U+FE0D VARIATION SELECTOR-14                      T2
    "\uFE0E",  # U+FE0E VARIATION SELECTOR-15                      T2
    "\uFE0F",  # U+FE0F VARIATION SELECTOR-16                      T2
    "\U000E0001",  # U+E0001 LANGUAGE TAG                               T3
    "\U000E0020",  # U+E0020 TAG SPACE                                  T3
    "\U000E0021",  # U+E0021 TAG EXCLAMATION MARK                       T3
    "\U000E0022",  # U+E0022 TAG QUOTATION MARK                         T3
    "\U000E0023",  # U+E0023 TAG NUMBER SIGN                            T3
    "\U000E0024",  # U+E0024 TAG DOLLAR SIGN                            T3
    "\U000E0025",  # U+E0025 TAG PERCENT SIGN                           T3
    "\U000E0026",  # U+E0026 TAG AMPERSAND                              T3
    "\U000E0027",  # U+E0027 TAG APOSTROPHE                             T3
    "\U000E0028",  # U+E0028 TAG LEFT PARENTHESIS                       T3
    "\U000E0029",  # U+E0029 TAG RIGHT PARENTHESIS                      T3
    "\U000E002A",  # U+E002A TAG ASTERISK                               T3
    "\U000E002B",  # U+E002B TAG PLUS SIGN                              T3
    "\U000E002C",  # U+E002C TAG COMMA                                  T3
    "\U000E002D",  # U+E002D TAG HYPHEN-MINUS                           T3
    "\U000E002E",  # U+E002E TAG FULL STOP                              T3
    "\U000E002F",  # U+E002F TAG SOLIDUS                                T3
    "\U000E0030",  # U+E0030 TAG DIGIT ZERO                             T3
    "\U000E0031",  # U+E0031 TAG DIGIT ONE                              T3
    "\U000E0032",  # U+E0032 TAG DIGIT TWO                              T3
    "\U000E0033",  # U+E0033 TAG DIGIT THREE                            T3
    "\U000E0034",  # U+E0034 TAG DIGIT FOUR                             T3
    "\U000E0035",  # U+E0035 TAG DIGIT FIVE                             T3
    "\U000E0036",  # U+E0036 TAG DIGIT SIX                              T3
    "\U000E0037",  # U+E0037 TAG DIGIT SEVEN                            T3
    "\U000E0038",  # U+E0038 TAG DIGIT EIGHT                            T3
    "\U000E0039",  # U+E0039 TAG DIGIT NINE                             T3
    "\U000E003A",  # U+E003A TAG COLON                                  T3
    "\U000E003B",  # U+E003B TAG SEMICOLON                              T3
    "\U000E003C",  # U+E003C TAG LESS-THAN SIGN                         T3
    "\U000E003D",  # U+E003D TAG EQUALS SIGN                            T3
    "\U000E003E",  # U+E003E TAG GREATER-THAN SIGN                      T3
    "\U000E003F",  # U+E003F TAG QUESTION MARK                          T3
    "\U000E0040",  # U+E0040 TAG COMMERCIAL AT                          T3
    "\U000E0041",  # U+E0041 TAG LATIN CAPITAL LETTER A                 T3
    "\U000E0042",  # U+E0042 TAG LATIN CAPITAL LETTER B                 T3
    "\U000E0043",  # U+E0043 TAG LATIN CAPITAL LETTER C                 T3
    "\U000E0044",  # U+E0044 TAG LATIN CAPITAL LETTER D                 T3
    "\U000E0045",  # U+E0045 TAG LATIN CAPITAL LETTER E                 T3
    "\U000E0046",  # U+E0046 TAG LATIN CAPITAL LETTER F                 T3
    "\U000E0047",  # U+E0047 TAG LATIN CAPITAL LETTER G                 T3
    "\U000E0048",  # U+E0048 TAG LATIN CAPITAL LETTER H                 T3
    "\U000E0049",  # U+E0049 TAG LATIN CAPITAL LETTER I                 T3
    "\U000E004A",  # U+E004A TAG LATIN CAPITAL LETTER J                 T3
    "\U000E004B",  # U+E004B TAG LATIN CAPITAL LETTER K                 T3
    "\U000E004C",  # U+E004C TAG LATIN CAPITAL LETTER L                 T3
    "\U000E004D",  # U+E004D TAG LATIN CAPITAL LETTER M                 T3
    "\U000E004E",  # U+E004E TAG LATIN CAPITAL LETTER N                 T3
    "\U000E004F",  # U+E004F TAG LATIN CAPITAL LETTER O                 T3
    "\U000E0050",  # U+E0050 TAG LATIN CAPITAL LETTER P                 T3
    "\U000E0051",  # U+E0051 TAG LATIN CAPITAL LETTER Q                 T3
    "\U000E0052",  # U+E0052 TAG LATIN CAPITAL LETTER R                 T3
    "\U000E0053",  # U+E0053 TAG LATIN CAPITAL LETTER S                 T3
    "\U000E0054",  # U+E0054 TAG LATIN CAPITAL LETTER T                 T3
    "\U000E0055",  # U+E0055 TAG LATIN CAPITAL LETTER U                 T3
    "\U000E0056",  # U+E0056 TAG LATIN CAPITAL LETTER V                 T3
    "\U000E0057",  # U+E0057 TAG LATIN CAPITAL LETTER W                 T3
    "\U000E0058",  # U+E0058 TAG LATIN CAPITAL LETTER X                 T3
    "\U000E0059",  # U+E0059 TAG LATIN CAPITAL LETTER Y                 T3
    "\U000E005A",  # U+E005A TAG LATIN CAPITAL LETTER Z                 T3
    "\U000E005B",  # U+E005B TAG LEFT SQUARE BRACKET                    T3
    "\U000E005C",  # U+E005C TAG REVERSE SOLIDUS                        T3
    "\U000E005D",  # U+E005D TAG RIGHT SQUARE BRACKET                   T3
    "\U000E005E",  # U+E005E TAG CIRCUMFLEX ACCENT                      T3
    "\U000E005F",  # U+E005F TAG LOW LINE                               T3
    "\U000E0060",  # U+E0060 TAG GRAVE ACCENT                           T3
    "\U000E0061",  # U+E0061 TAG LATIN SMALL LETTER A                   T3
    "\U000E0062",  # U+E0062 TAG LATIN SMALL LETTER B                   T3
    "\U000E0063",  # U+E0063 TAG LATIN SMALL LETTER C                   T3
    "\U000E0064",  # U+E0064 TAG LATIN SMALL LETTER D                   T3
    "\U000E0065",  # U+E0065 TAG LATIN SMALL LETTER E                   T3
    "\U000E0066",  # U+E0066 TAG LATIN SMALL LETTER F                   T3
    "\U000E0067",  # U+E0067 TAG LATIN SMALL LETTER G                   T3
    "\U000E0068",  # U+E0068 TAG LATIN SMALL LETTER H                   T3
    "\U000E0069",  # U+E0069 TAG LATIN SMALL LETTER I                   T3
    "\U000E006A",  # U+E006A TAG LATIN SMALL LETTER J                   T3
    "\U000E006B",  # U+E006B TAG LATIN SMALL LETTER K                   T3
    "\U000E006C",  # U+E006C TAG LATIN SMALL LETTER L                   T3
    "\U000E006D",  # U+E006D TAG LATIN SMALL LETTER M                   T3
    "\U000E006E",  # U+E006E TAG LATIN SMALL LETTER N                   T3
    "\U000E006F",  # U+E006F TAG LATIN SMALL LETTER O                   T3
    "\U000E0070",  # U+E0070 TAG LATIN SMALL LETTER P                   T3
    "\U000E0071",  # U+E0071 TAG LATIN SMALL LETTER Q                   T3
    "\U000E0072",  # U+E0072 TAG LATIN SMALL LETTER R                   T3
    "\U000E0073",  # U+E0073 TAG LATIN SMALL LETTER S                   T3
    "\U000E0074",  # U+E0074 TAG LATIN SMALL LETTER T                   T3
    "\U000E0075",  # U+E0075 TAG LATIN SMALL LETTER U                   T3
    "\U000E0076",  # U+E0076 TAG LATIN SMALL LETTER V                   T3
    "\U000E0077",  # U+E0077 TAG LATIN SMALL LETTER W                   T3
    "\U000E0078",  # U+E0078 TAG LATIN SMALL LETTER X                   T3
    "\U000E0079",  # U+E0079 TAG LATIN SMALL LETTER Y                   T3
    "\U000E007A",  # U+E007A TAG LATIN SMALL LETTER Z                   T3
    "\U000E007B",  # U+E007B TAG LEFT CURLY BRACKET                     T3
    "\U000E007C",  # U+E007C TAG VERTICAL LINE                          T3
    "\U000E007D",  # U+E007D TAG RIGHT CURLY BRACKET                    T3
    "\U000E007E",  # U+E007E TAG TILDE                                  T3
    "\U000E007F",  # U+E007F CANCEL TAG                                 T3
    "\U000E0100",  # U+E0100 VARIATION SELECTOR-17                      T3
    "\U000E0101",  # U+E0101 VARIATION SELECTOR-18                      T3
    "\U000E0102",  # U+E0102 VARIATION SELECTOR-19                      T3
    "\U000E0103",  # U+E0103 VARIATION SELECTOR-20                      T3
    "\U000E0104",  # U+E0104 VARIATION SELECTOR-21                      T3
    "\U000E0105",  # U+E0105 VARIATION SELECTOR-22                      T3
    "\U000E0106",  # U+E0106 VARIATION SELECTOR-23                      T3
    "\U000E0107",  # U+E0107 VARIATION SELECTOR-24                      T3
    "\U000E0108",  # U+E0108 VARIATION SELECTOR-25                      T3
    "\U000E0109",  # U+E0109 VARIATION SELECTOR-26                      T3
    "\U000E010A",  # U+E010A VARIATION SELECTOR-27                      T3
    "\U000E010B",  # U+E010B VARIATION SELECTOR-28                      T3
    "\U000E010C",  # U+E010C VARIATION SELECTOR-29                      T3
    "\U000E010D",  # U+E010D VARIATION SELECTOR-30                      T3
    "\U000E010E",  # U+E010E VARIATION SELECTOR-31                      T3
    "\U000E010F",  # U+E010F VARIATION SELECTOR-32                      T3
    "\U000E0110",  # U+E0110 VARIATION SELECTOR-33                      T3
    "\U000E0111",  # U+E0111 VARIATION SELECTOR-34                      T3
    "\U000E0112",  # U+E0112 VARIATION SELECTOR-35                      T3
    "\U000E0113",  # U+E0113 VARIATION SELECTOR-36                      T3
    "\U000E0114",  # U+E0114 VARIATION SELECTOR-37                      T3
    "\U000E0115",  # U+E0115 VARIATION SELECTOR-38                      T3
    "\U000E0116",  # U+E0116 VARIATION SELECTOR-39                      T3
    "\U000E0117",  # U+E0117 VARIATION SELECTOR-40                      T3
    "\U000E0118",  # U+E0118 VARIATION SELECTOR-41                      T3
    "\U000E0119",  # U+E0119 VARIATION SELECTOR-42                      T3
    "\U000E011A",  # U+E011A VARIATION SELECTOR-43                      T3
    "\U000E011B",  # U+E011B VARIATION SELECTOR-44                      T3
    "\U000E011C",  # U+E011C VARIATION SELECTOR-45                      T3
    "\U000E011D",  # U+E011D VARIATION SELECTOR-46                      T3
    "\U000E011E",  # U+E011E VARIATION SELECTOR-47                      T3
    "\U000E011F",  # U+E011F VARIATION SELECTOR-48                      T3
    "\U000E0120",  # U+E0120 VARIATION SELECTOR-49                      T3
    "\U000E0121",  # U+E0121 VARIATION SELECTOR-50                      T3
    "\U000E0122",  # U+E0122 VARIATION SELECTOR-51                      T3
    "\U000E0123",  # U+E0123 VARIATION SELECTOR-52                      T3
    "\U000E0124",  # U+E0124 VARIATION SELECTOR-53                      T3
    "\U000E0125",  # U+E0125 VARIATION SELECTOR-54                      T3
    "\U000E0126",  # U+E0126 VARIATION SELECTOR-55                      T3
    "\U000E0127",  # U+E0127 VARIATION SELECTOR-56                      T3
    "\U000E0128",  # U+E0128 VARIATION SELECTOR-57                      T3
    "\U000E0129",  # U+E0129 VARIATION SELECTOR-58                      T3
    "\U000E012A",  # U+E012A VARIATION SELECTOR-59                      T3
    "\U000E012B",  # U+E012B VARIATION SELECTOR-60                      T3
    "\U000E012C",  # U+E012C VARIATION SELECTOR-61                      T3
    "\U000E012D",  # U+E012D VARIATION SELECTOR-62                      T3
    "\U000E012E",  # U+E012E VARIATION SELECTOR-63                      T3
    "\U000E012F",  # U+E012F VARIATION SELECTOR-64                      T3
    "\U000E0130",  # U+E0130 VARIATION SELECTOR-65                      T3
    "\U000E0131",  # U+E0131 VARIATION SELECTOR-66                      T3
    "\U000E0132",  # U+E0132 VARIATION SELECTOR-67                      T3
    "\U000E0133",  # U+E0133 VARIATION SELECTOR-68                      T3
    "\U000E0134",  # U+E0134 VARIATION SELECTOR-69                      T3
    "\U000E0135",  # U+E0135 VARIATION SELECTOR-70                      T3
    "\U000E0136",  # U+E0136 VARIATION SELECTOR-71                      T3
    "\U000E0137",  # U+E0137 VARIATION SELECTOR-72                      T3
    "\U000E0138",  # U+E0138 VARIATION SELECTOR-73                      T3
    "\U000E0139",  # U+E0139 VARIATION SELECTOR-74                      T3
    "\U000E013A",  # U+E013A VARIATION SELECTOR-75                      T3
    "\U000E013B",  # U+E013B VARIATION SELECTOR-76                      T3
    "\U000E013C",  # U+E013C VARIATION SELECTOR-77                      T3
    "\U000E013D",  # U+E013D VARIATION SELECTOR-78                      T3
    "\U000E013E",  # U+E013E VARIATION SELECTOR-79                      T3
    "\U000E013F",  # U+E013F VARIATION SELECTOR-80                      T3
    "\U000E0140",  # U+E0140 VARIATION SELECTOR-81                      T3
    "\U000E0141",  # U+E0141 VARIATION SELECTOR-82                      T3
    "\U000E0142",  # U+E0142 VARIATION SELECTOR-83                      T3
    "\U000E0143",  # U+E0143 VARIATION SELECTOR-84                      T3
    "\U000E0144",  # U+E0144 VARIATION SELECTOR-85                      T3
    "\U000E0145",  # U+E0145 VARIATION SELECTOR-86                      T3
    "\U000E0146",  # U+E0146 VARIATION SELECTOR-87                      T3
    "\U000E0147",  # U+E0147 VARIATION SELECTOR-88                      T3
    "\U000E0148",  # U+E0148 VARIATION SELECTOR-89                      T3
    "\U000E0149",  # U+E0149 VARIATION SELECTOR-90                      T3
    "\U000E014A",  # U+E014A VARIATION SELECTOR-91                      T3
    "\U000E014B",  # U+E014B VARIATION SELECTOR-92                      T3
    "\U000E014C",  # U+E014C VARIATION SELECTOR-93                      T3
    "\U000E014D",  # U+E014D VARIATION SELECTOR-94                      T3
    "\U000E014E",  # U+E014E VARIATION SELECTOR-95                      T3
    "\U000E014F",  # U+E014F VARIATION SELECTOR-96                      T3
    "\U000E0150",  # U+E0150 VARIATION SELECTOR-97                      T3
    "\U000E0151",  # U+E0151 VARIATION SELECTOR-98                      T3
    "\U000E0152",  # U+E0152 VARIATION SELECTOR-99                      T3
    "\U000E0153",  # U+E0153 VARIATION SELECTOR-100                     T3
    "\U000E0154",  # U+E0154 VARIATION SELECTOR-101                     T3
    "\U000E0155",  # U+E0155 VARIATION SELECTOR-102                     T3
    "\U000E0156",  # U+E0156 VARIATION SELECTOR-103                     T3
    "\U000E0157",  # U+E0157 VARIATION SELECTOR-104                     T3
    "\U000E0158",  # U+E0158 VARIATION SELECTOR-105                     T3
    "\U000E0159",  # U+E0159 VARIATION SELECTOR-106                     T3
    "\U000E015A",  # U+E015A VARIATION SELECTOR-107                     T3
    "\U000E015B",  # U+E015B VARIATION SELECTOR-108                     T3
    "\U000E015C",  # U+E015C VARIATION SELECTOR-109                     T3
    "\U000E015D",  # U+E015D VARIATION SELECTOR-110                     T3
    "\U000E015E",  # U+E015E VARIATION SELECTOR-111                     T3
    "\U000E015F",  # U+E015F VARIATION SELECTOR-112                     T3
    "\U000E0160",  # U+E0160 VARIATION SELECTOR-113                     T3
    "\U000E0161",  # U+E0161 VARIATION SELECTOR-114                     T3
    "\U000E0162",  # U+E0162 VARIATION SELECTOR-115                     T3
    "\U000E0163",  # U+E0163 VARIATION SELECTOR-116                     T3
    "\U000E0164",  # U+E0164 VARIATION SELECTOR-117                     T3
    "\U000E0165",  # U+E0165 VARIATION SELECTOR-118                     T3
    "\U000E0166",  # U+E0166 VARIATION SELECTOR-119                     T3
    "\U000E0167",  # U+E0167 VARIATION SELECTOR-120                     T3
    "\U000E0168",  # U+E0168 VARIATION SELECTOR-121                     T3
    "\U000E0169",  # U+E0169 VARIATION SELECTOR-122                     T3
    "\U000E016A",  # U+E016A VARIATION SELECTOR-123                     T3
    "\U000E016B",  # U+E016B VARIATION SELECTOR-124                     T3
    "\U000E016C",  # U+E016C VARIATION SELECTOR-125                     T3
    "\U000E016D",  # U+E016D VARIATION SELECTOR-126                     T3
    "\U000E016E",  # U+E016E VARIATION SELECTOR-127                     T3
    "\U000E016F",  # U+E016F VARIATION SELECTOR-128                     T3
    "\U000E0170",  # U+E0170 VARIATION SELECTOR-129                     T3
    "\U000E0171",  # U+E0171 VARIATION SELECTOR-130                     T3
    "\U000E0172",  # U+E0172 VARIATION SELECTOR-131                     T3
    "\U000E0173",  # U+E0173 VARIATION SELECTOR-132                     T3
    "\U000E0174",  # U+E0174 VARIATION SELECTOR-133                     T3
    "\U000E0175",  # U+E0175 VARIATION SELECTOR-134                     T3
    "\U000E0176",  # U+E0176 VARIATION SELECTOR-135                     T3
    "\U000E0177",  # U+E0177 VARIATION SELECTOR-136                     T3
    "\U000E0178",  # U+E0178 VARIATION SELECTOR-137                     T3
    "\U000E0179",  # U+E0179 VARIATION SELECTOR-138                     T3
    "\U000E017A",  # U+E017A VARIATION SELECTOR-139                     T3
    "\U000E017B",  # U+E017B VARIATION SELECTOR-140                     T3
    "\U000E017C",  # U+E017C VARIATION SELECTOR-141                     T3
    "\U000E017D",  # U+E017D VARIATION SELECTOR-142                     T3
    "\U000E017E",  # U+E017E VARIATION SELECTOR-143                     T3
    "\U000E017F",  # U+E017F VARIATION SELECTOR-144                     T3
    "\U000E0180",  # U+E0180 VARIATION SELECTOR-145                     T3
    "\U000E0181",  # U+E0181 VARIATION SELECTOR-146                     T3
    "\U000E0182",  # U+E0182 VARIATION SELECTOR-147                     T3
    "\U000E0183",  # U+E0183 VARIATION SELECTOR-148                     T3
    "\U000E0184",  # U+E0184 VARIATION SELECTOR-149                     T3
    "\U000E0185",  # U+E0185 VARIATION SELECTOR-150                     T3
    "\U000E0186",  # U+E0186 VARIATION SELECTOR-151                     T3
    "\U000E0187",  # U+E0187 VARIATION SELECTOR-152                     T3
    "\U000E0188",  # U+E0188 VARIATION SELECTOR-153                     T3
    "\U000E0189",  # U+E0189 VARIATION SELECTOR-154                     T3
    "\U000E018A",  # U+E018A VARIATION SELECTOR-155                     T3
    "\U000E018B",  # U+E018B VARIATION SELECTOR-156                     T3
    "\U000E018C",  # U+E018C VARIATION SELECTOR-157                     T3
    "\U000E018D",  # U+E018D VARIATION SELECTOR-158                     T3
    "\U000E018E",  # U+E018E VARIATION SELECTOR-159                     T3
    "\U000E018F",  # U+E018F VARIATION SELECTOR-160                     T3
    "\U000E0190",  # U+E0190 VARIATION SELECTOR-161                     T3
    "\U000E0191",  # U+E0191 VARIATION SELECTOR-162                     T3
    "\U000E0192",  # U+E0192 VARIATION SELECTOR-163                     T3
    "\U000E0193",  # U+E0193 VARIATION SELECTOR-164                     T3
    "\U000E0194",  # U+E0194 VARIATION SELECTOR-165                     T3
    "\U000E0195",  # U+E0195 VARIATION SELECTOR-166                     T3
    "\U000E0196",  # U+E0196 VARIATION SELECTOR-167                     T3
    "\U000E0197",  # U+E0197 VARIATION SELECTOR-168                     T3
    "\U000E0198",  # U+E0198 VARIATION SELECTOR-169                     T3
    "\U000E0199",  # U+E0199 VARIATION SELECTOR-170                     T3
    "\U000E019A",  # U+E019A VARIATION SELECTOR-171                     T3
    "\U000E019B",  # U+E019B VARIATION SELECTOR-172                     T3
    "\U000E019C",  # U+E019C VARIATION SELECTOR-173                     T3
    "\U000E019D",  # U+E019D VARIATION SELECTOR-174                     T3
    "\U000E019E",  # U+E019E VARIATION SELECTOR-175                     T3
    "\U000E019F",  # U+E019F VARIATION SELECTOR-176                     T3
    "\U000E01A0",  # U+E01A0 VARIATION SELECTOR-177                     T3
    "\U000E01A1",  # U+E01A1 VARIATION SELECTOR-178                     T3
    "\U000E01A2",  # U+E01A2 VARIATION SELECTOR-179                     T3
    "\U000E01A3",  # U+E01A3 VARIATION SELECTOR-180                     T3
    "\U000E01A4",  # U+E01A4 VARIATION SELECTOR-181                     T3
    "\U000E01A5",  # U+E01A5 VARIATION SELECTOR-182                     T3
    "\U000E01A6",  # U+E01A6 VARIATION SELECTOR-183                     T3
    "\U000E01A7",  # U+E01A7 VARIATION SELECTOR-184                     T3
    "\U000E01A8",  # U+E01A8 VARIATION SELECTOR-185                     T3
    "\U000E01A9",  # U+E01A9 VARIATION SELECTOR-186                     T3
    "\U000E01AA",  # U+E01AA VARIATION SELECTOR-187                     T3
    "\U000E01AB",  # U+E01AB VARIATION SELECTOR-188                     T3
    "\U000E01AC",  # U+E01AC VARIATION SELECTOR-189                     T3
    "\U000E01AD",  # U+E01AD VARIATION SELECTOR-190                     T3
    "\U000E01AE",  # U+E01AE VARIATION SELECTOR-191                     T3
    "\U000E01AF",  # U+E01AF VARIATION SELECTOR-192                     T3
    "\U000E01B0",  # U+E01B0 VARIATION SELECTOR-193                     T3
    "\U000E01B1",  # U+E01B1 VARIATION SELECTOR-194                     T3
    "\U000E01B2",  # U+E01B2 VARIATION SELECTOR-195                     T3
    "\U000E01B3",  # U+E01B3 VARIATION SELECTOR-196                     T3
    "\U000E01B4",  # U+E01B4 VARIATION SELECTOR-197                     T3
    "\U000E01B5",  # U+E01B5 VARIATION SELECTOR-198                     T3
    "\U000E01B6",  # U+E01B6 VARIATION SELECTOR-199                     T3
    "\U000E01B7",  # U+E01B7 VARIATION SELECTOR-200                     T3
    "\U000E01B8",  # U+E01B8 VARIATION SELECTOR-201                     T3
    "\U000E01B9",  # U+E01B9 VARIATION SELECTOR-202                     T3
    "\U000E01BA",  # U+E01BA VARIATION SELECTOR-203                     T3
    "\U000E01BB",  # U+E01BB VARIATION SELECTOR-204                     T3
    "\U000E01BC",  # U+E01BC VARIATION SELECTOR-205                     T3
    "\U000E01BD",  # U+E01BD VARIATION SELECTOR-206                     T3
    "\U000E01BE",  # U+E01BE VARIATION SELECTOR-207                     T3
    "\U000E01BF",  # U+E01BF VARIATION SELECTOR-208                     T3
    "\U000E01C0",  # U+E01C0 VARIATION SELECTOR-209                     T3
    "\U000E01C1",  # U+E01C1 VARIATION SELECTOR-210                     T3
    "\U000E01C2",  # U+E01C2 VARIATION SELECTOR-211                     T3
    "\U000E01C3",  # U+E01C3 VARIATION SELECTOR-212                     T3
    "\U000E01C4",  # U+E01C4 VARIATION SELECTOR-213                     T3
    "\U000E01C5",  # U+E01C5 VARIATION SELECTOR-214                     T3
    "\U000E01C6",  # U+E01C6 VARIATION SELECTOR-215                     T3
    "\U000E01C7",  # U+E01C7 VARIATION SELECTOR-216                     T3
    "\U000E01C8",  # U+E01C8 VARIATION SELECTOR-217                     T3
    "\U000E01C9",  # U+E01C9 VARIATION SELECTOR-218                     T3
    "\U000E01CA",  # U+E01CA VARIATION SELECTOR-219                     T3
    "\U000E01CB",  # U+E01CB VARIATION SELECTOR-220                     T3
    "\U000E01CC",  # U+E01CC VARIATION SELECTOR-221                     T3
    "\U000E01CD",  # U+E01CD VARIATION SELECTOR-222                     T3
    "\U000E01CE",  # U+E01CE VARIATION SELECTOR-223                     T3
    "\U000E01CF",  # U+E01CF VARIATION SELECTOR-224                     T3
    "\U000E01D0",  # U+E01D0 VARIATION SELECTOR-225                     T3
    "\U000E01D1",  # U+E01D1 VARIATION SELECTOR-226                     T3
    "\U000E01D2",  # U+E01D2 VARIATION SELECTOR-227                     T3
    "\U000E01D3",  # U+E01D3 VARIATION SELECTOR-228                     T3
    "\U000E01D4",  # U+E01D4 VARIATION SELECTOR-229                     T3
    "\U000E01D5",  # U+E01D5 VARIATION SELECTOR-230                     T3
    "\U000E01D6",  # U+E01D6 VARIATION SELECTOR-231                     T3
    "\U000E01D7",  # U+E01D7 VARIATION SELECTOR-232                     T3
    "\U000E01D8",  # U+E01D8 VARIATION SELECTOR-233                     T3
    "\U000E01D9",  # U+E01D9 VARIATION SELECTOR-234                     T3
    "\U000E01DA",  # U+E01DA VARIATION SELECTOR-235                     T3
    "\U000E01DB",  # U+E01DB VARIATION SELECTOR-236                     T3
    "\U000E01DC",  # U+E01DC VARIATION SELECTOR-237                     T3
    "\U000E01DD",  # U+E01DD VARIATION SELECTOR-238                     T3
    "\U000E01DE",  # U+E01DE VARIATION SELECTOR-239                     T3
    "\U000E01DF",  # U+E01DF VARIATION SELECTOR-240                     T3
    "\U000E01E0",  # U+E01E0 VARIATION SELECTOR-241                     T3
    "\U000E01E1",  # U+E01E1 VARIATION SELECTOR-242                     T3
    "\U000E01E2",  # U+E01E2 VARIATION SELECTOR-243                     T3
    "\U000E01E3",  # U+E01E3 VARIATION SELECTOR-244                     T3
    "\U000E01E4",  # U+E01E4 VARIATION SELECTOR-245                     T3
    "\U000E01E5",  # U+E01E5 VARIATION SELECTOR-246                     T3
    "\U000E01E6",  # U+E01E6 VARIATION SELECTOR-247                     T3
    "\U000E01E7",  # U+E01E7 VARIATION SELECTOR-248                     T3
    "\U000E01E8",  # U+E01E8 VARIATION SELECTOR-249                     T3
    "\U000E01E9",  # U+E01E9 VARIATION SELECTOR-250                     T3
    "\U000E01EA",  # U+E01EA VARIATION SELECTOR-251                     T3
    "\U000E01EB",  # U+E01EB VARIATION SELECTOR-252                     T3
    "\U000E01EC",  # U+E01EC VARIATION SELECTOR-253                     T3
    "\U000E01ED",  # U+E01ED VARIATION SELECTOR-254                     T3
    "\U000E01EE",  # U+E01EE VARIATION SELECTOR-255                     T3
    "\U000E01EF",  # U+E01EF VARIATION SELECTOR-256                     T3
]

# ── Usage in stego_v2.py ──────────────────────────────────────────────
# Replace the three profile lists with the validated versions above:
#
#   _SAFE_CHARS     = _VALIDATED_SAFE_CHARS
#   _EXTENDED_CHARS = _VALIDATED_EXTENDED_CHARS
#   _MAX_CHARS      = _VALIDATED_MAX_CHARS
#
# Then update the three slice-derived variables:
#   _VS_CHARS  = []   # already included in _EXTENDED
#   _TAG_CHARS = []   # already included in _MAX